import {useEffect,useState,useRef} from 'react';
import {Globe,Layers,ShoppingBag,FileText,Calendar,ListChecks,ExternalLink} from 'lucide-react';
import {Action,Field,Message} from './Experience';

const choices=[{id:'funnel',title:'Funnels',icon:Layers},{id:'website',title:'Websites',icon:Globe},{id:'store',title:'Stores',icon:ShoppingBag},{id:'external',title:'External website',icon:ExternalLink},{id:'form',title:'Forms',icon:FileText},{id:'survey',title:'Surveys',icon:ListChecks},{id:'calendar',title:'Calendars',icon:Calendar},{id:'native',title:'Hosted referral form',icon:FileText}];
export function sourceLabel(row:any){return row.tracking_policy?.source?.selection?.name||(row.conversion_mode==='native'?'Hosted referral form':'External website');}
export default function CampaignSource({value,onChange}:{value:any;onChange:(patch:Record<string,any>)=>void}){
 const kind=value.sourceKind||value.source?.selection?.kind||(value.conversionMode==='external'?'external':'native');
 const connected=!['native','external'].includes(kind),[rows,setRows]=useState<any[]>([]),[page,setPage]=useState(1),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[q,setQ]=useState('');
 useEffect(()=>{if(!connected)return;const c=new AbortController();setBusy(true);setError('');fetch(`/api/operations?${new URLSearchParams({resource:'campaignCatalog',kind,page:String(page)})}`,{signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.message||'Assets could not be loaded.');return b;}).then(b=>{if(!c.signal.aborted){setRows(old=>page===1?b.rows:[...old,...b.rows.filter((r:any)=>!old.some(x=>x.id===r.id))]);setMore(b.hasMore);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[kind,page,retry,connected]);
 const requestRevision=useRef(0);
 async function loadPage(source:any){const revision=++requestRevision.current;setBusy(true);setError('');try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'loadCampaignPage',data:{source}})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Published page could not be loaded.');if(revision===requestRevision.current)onChange({source:result.source,destinationUrl:result.destinationUrl||'',automation:result.products?.length?(value.automation&&value.automation!=='off'?value.automation:'auto'):'off'});}catch(e){if(revision===requestRevision.current)setError((e as Error).message);}finally{if(revision===requestRevision.current)setBusy(false);}}
 const selected=value.source?.selection,landing=selected?.pages?.find((p:any)=>p.id===value.source?.pageId),path=landing?.path||selected?.url||'';
 function destination(nextPath:string){if(nextPath.startsWith('https://'))return nextPath;try{if(value.destinationUrl&&nextPath)return new URL(nextPath,new URL(value.destinationUrl).origin).toString();}catch{}return '';}
 return <section className="st-source-picker"><h3>Where should your salesman’s links lead?</h3><p className="st-help">Choose one source, then select the page visitors will see.</p><div className="st-choice-grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))'}}>{choices.map(c=><button key={c.id} type="button" aria-pressed={kind===c.id} className={`st-choice ${kind===c.id?'is-selected':''}`} onClick={()=>{requestRevision.current++;setPage(1);setRows([]);setQ('');setError('');onChange({sourceKind:c.id,conversionMode:c.id==='native'?'native':'external',source:null,destinationUrl:'',automation:'off'});}}><c.icon size={21}/><strong>{c.title}</strong></button>)}</div>
 {connected&&<div className="st-disclosure"><Field label="Search connected assets"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name"/></Field><Field label={`Select ${choices.find(c=>c.id===kind)?.title.toLowerCase()} *`}><select required disabled={busy&&rows.length===0} value={selected?.id||''} onChange={e=>{requestRevision.current++;const r=rows.find(r=>r.id===e.target.value);onChange({source:r?{selection:r.selection,proof:r.proof,pageId:null}:null,destinationUrl:r?.url?.startsWith('https://')?r.url:'',automation:'off'});}}><option value="">Choose an asset</option>{selected&&!rows.some(r=>r.id===selected.id)&&<option value={selected.id}>{selected.name} (saved)</option>}{rows.filter(r=>r.name.toLowerCase().includes(q.toLowerCase())||r.id===selected?.id).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>{busy&&<p role="status">Loading your connected assets…</p>}<Message error={error}/>{error&&<Action onClick={()=>setRetry(n=>n+1)}>Retry loading</Action>}{!busy&&!error&&!rows.length&&<p>No {kind} assets found on this page. Create and publish one in GHL, then refresh.</p>}{more&&<Action disabled={busy} onClick={()=>setPage(n=>n+1)}>Load more assets</Action>}
 {selected&&['funnel','website','store'].includes(kind)&&<Field label="First page visitors land on *"><select required value={value.source?.pageId||''} onChange={e=>{const p=selected.pages.find((p:any)=>p.id===e.target.value);const source={...value.source,pageId:p?.id||null};onChange({source,destinationUrl:p?destination(p.path):'',automation:'off'});if(p)void loadPage(source);}}><option value="">Choose a landing page</option>{selected.pages.map((p:any)=><option key={p.id} value={p.id}>{p.name} — {p.path}</option>)}</select></Field>}{path&&<p className="st-help">Selected page path: <strong>{path}</strong></p>}</div>}
 {kind!=='native'&&<><Field label="Published landing page URL *" hint={selected?.checkout?.url?'Loaded automatically from your selected page.':connected?'Enter the published URL if your page does not have a domain yet.':'Enter the page your salesman will promote.'}><input type="url" required readOnly={!!selected?.checkout?.url} value={value.destinationUrl||''} placeholder={path.startsWith('/')?`https://your-domain.com${path}`:'https://your-domain.com/offer'} onChange={e=>onChange({destinationUrl:e.target.value})}/></Field><p className="st-help">Each salesman gets a unique tracking link. Visits are recorded before opening this page. Sales commission is recorded after a verified payment or conversion is received.</p></>}
 {connected&&selected&&!selected.checkout&&<p className="st-setup-banner">Asset selected. Submission tracking still needs a verified connection. Forms, surveys and calendar bookings create leads; commission requires a qualifying payment or a configured lead award. Use the campaign’s test submission check for forms and surveys. Other source events are configured in Settings → Funnels, events, tax forms & exports.</p>}
 {selected?.checkout&&!selected.checkout.products?.length&&<p className="st-setup-banner">No eligible checkout products were found. This page can track visits, but automatic sales commissions are off. Publish the page, configure its products, then reload the selected page before testing a purchase.</p>}
 {selected?.checkout?.products?.length>0&&<div className="st-disclosure"><h3>Commission-eligible products</h3><p className="st-help">Loaded from your selected source. Commission rates are set in the next step; the actual paid amount is verified after checkout.</p><table className="st-table"><thead><tr><th>Product</th><th>Type</th><th>Price</th></tr></thead><tbody>{selected.checkout.products.map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{p.type==='store'?'Store product':p.type==='recurring'?'Recurring':'One-time'}</td><td>{p.amount===null?'Calculated at checkout':`${p.currency} ${p.amount}`}</td></tr>)}</tbody></table><Field label="Automatic checkout tracking"><select value={value.automation||'auto'} onChange={e=>onChange({automation:e.target.value})}><option value="auto">Automatic — follow the checkout’s test or live mode</option><option value="test">Test purchases only</option><option value="live">Live purchases — post verified commissions</option><option value="off">Off — track visits only</option></select></Field><p className="st-help">Purchases are verified automatically. Test orders appear on the Dashboard with a Test label; only live payments create payable commissions. The selected website or funnel needs the one-time connection setup shown after saving.</p></div>}
 {kind==='native'&&<p className="st-help">Visitors complete your hosted referral form. Their referral is captured in Leads & clients. A form submission is not a paid order; sales commission is earned when a qualifying payment is recorded.</p>}
 </section>;
}
