const SalesChart=lazy(()=>import('./SalesChart'));
import {lazy,Suspense,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useTracker} from '../TrackerGate';
import {displayMinor} from '../../lib/exact-commission';
import {Action,Empty,Message,Pager,Tabs,useRemote} from './Experience';

export default function CampaignActivity({campaignId='',salespersonId='',from='',to='',initialMode='all',dashboard=false,refreshToken=0}:{campaignId?:string;salespersonId?:string;from?:string;to?:string;initialMode?:string;dashboard?:boolean;refreshToken?:number}){
 const {workspace}=useTracker(),digits=workspace?.payout_terms?.minorDigits??2;
 const [person,setPerson]=useState(salespersonId),[mode,setMode]=useState(initialMode),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 const people=useRemote('people',{limit:'100',sort:'name'}),params=new URLSearchParams({resource:'campaignActivity',includeSalesmen:dashboard?'1':'',includeAnalytics:dashboard?'1':'',campaignId,salespersonId:salespersonId||person,from,to,mode,page:String(page)}).toString();
 useEffect(()=>setPage(1),[campaignId,from,to,salespersonId]);
 useEffect(()=>{const controller=new AbortController();let active=false;setData(null);setError('');
  const refresh=async()=>{if(active||controller.signal.aborted)return;active=true;try{const response=await fetch('/api/operations?'+params,{signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.message||'Orders could not be loaded.');if(!controller.signal.aborted){setData(result);setError('');if(mode==='auto')setMode(result.summary.some((r:any)=>r.mode==='live'&&r.completed)?'live':'test');}}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{active=false;}};
  void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},15000);const focus=()=>{if(document.visibilityState==='visible')void refresh();};document.addEventListener('visibilitychange',focus);
  return()=>{controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',focus);};
 },[params,revision,refreshToken]);
 const money=(value:string,currency=workspace?.currency||'USD')=>displayMinor(value||'0',currency,digits);
 const groups=(kind:string)=>data?.summary.filter((r:any)=>r.mode===kind)||[];
 const selectedGroups=data?.summary.filter((r:any)=>r.mode===mode)||[];
 const modeTotal=(key:string)=>selectedGroups.filter((r:any)=>r.currency===workspace?.currency).reduce((n:bigint,r:any)=>n+BigInt(r[key]||'0'),0n).toString();
 const chart=(data?.trend||[]).filter((r:any)=>r.mode===mode&&r.currency===workspace?.currency).map((r:any)=>({...r,value:Number(r.revenue_minor)/10**digits}));
 const ranking=(data?.salesmen||[]).filter((r:any)=>r.mode===mode&&r.completed>0&&r.currency===workspace?.currency).sort((a:any,b:any)=>b.completed-a.completed||(BigInt(a.revenue_minor)>BigInt(b.revenue_minor)?-1:1)).slice(0,5);
 const successful=data?.summary.reduce((n:number,r:any)=>n+r.completed,0)||0;
 return <section className={`st-panel ${dashboard?'st-dashboard-activity':''}`} aria-label="Campaign tracking">
  <div className="st-panel-heading"><div><h2>{dashboard?'Sales overview':'Campaign tracking'}</h2><p className="st-help">{dashboard?'Orders, sales and your best-performing salesmen.':'Share a salesman’s link. Purchases appear here automatically.'}</p></div>{dashboard?<Tabs value={mode} onChange={v=>{setMode(v);setPage(1);}} tabs={[{id:'live',label:'Live'},{id:'test',label:'Test'}]}/>:<Link className="st-button" to="/people">Salesman affiliate links</Link>}</div>
  <Message error={error}/>
  {dashboard?<><div className={`st-mode-banner ${mode==='test'?'is-test':''}`}>{mode==='test'?'Test mode · Practice orders and commissions. No real money is payable.':'Live mode · Verified customer purchases and earned commissions.'}</div><div className="st-stats st-stats-four st-overview-cards">{[['Tracked visits',String(data?.clicks??'—')],['Completed orders',data?String(selectedGroups.reduce((n:number,r:any)=>n+r.completed,0)):'—'],['Sales',data?money(modeTotal('revenue_minor')):'—'],['Commission',data?money(modeTotal('commission_minor')):'—']].map(([label,value])=><div className="st-stat" key={label}><p>{label}</p><strong>{value}</strong></div>)}</div></>:<div className="st-stats st-stats-four" style={{padding:'0 20px'}}>
   <div className="st-stat st-small-stat"><p>Tracked visits</p><strong>{data?.clicks??'—'}</strong><small>Identified referral visits in this period</small></div>
   <div className="st-stat st-small-stat"><p>Completed orders</p><strong>{data?successful:'—'}</strong><small>Live and test orders, shown separately below</small></div>
   {['live','test'].map(kind=><div key={kind} className="st-stat st-small-stat"><p>{kind==='test'?'Test sales':'Live sales'}</p>{groups(kind).length?groups(kind).map((r:any)=><div key={r.currency}><strong>{money(r.revenue_minor,r.currency)}</strong><small>{money(r.commission_minor,r.currency)} {kind==='test'?'test commission':'commission'} · {r.completed} orders</small></div>):<><strong>{data?money('0'):'—'}</strong><small>{kind==='test'?'Practice purchases — never payable':'Verified collected revenue after refunds'}</small></>}</div>)}
  </div>}
  {dashboard&&<div className="st-dashboard-grid st-overview-insights"><section className="st-panel"><div className="st-panel-heading"><h2>Sales over time</h2><span className="st-muted">{mode==='test'?'Test sales':'Live sales'}</span></div>{chart.length?<Suspense fallback={<div className="st-chart st-loading" role="status">Loading chart…</div>}><SalesChart data={chart} money={money}/></Suspense>:<Empty title="No sales in this view" description="Choose Test to see practice orders, or change the date and campaign filters."/>}</section><section className="st-panel"><div className="st-panel-heading"><h2>Top salesmen</h2><span className="st-muted">By completed orders</span></div>{ranking.length?<div className="st-leaderboard">{ranking.map((r:any,i:number)=><div key={r.salesperson_id}><span className="st-rank">{i+1}</span><div><strong>{r.salesperson_name}</strong><small>{r.completed} {r.completed===1?'order':'orders'} · {money(r.commission_minor)} commission</small></div><b>{money(r.revenue_minor)}</b></div>)}</div>:<Empty title="No completed orders yet" description="Salesmen appear here when purchases are verified."/>}</section></div>}
  <div className="st-toolbar">{!dashboard&&<Tabs value={mode} onChange={v=>{setMode(v);setPage(1);}} tabs={[{id:'all',label:'All orders'},{id:'live',label:'Live orders'},{id:'test',label:'Test orders'}]}/> }{dashboard&&<h2>Recent orders</h2>}{!salespersonId&&<label>Salesman <select className="st-select" aria-label="Order salesman" value={person} onChange={e=>{setPerson(e.target.value);setPage(1);}}><option value="">All salesmen</option>{people.data?.rows.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<Action onClick={()=>setRevision(r=>r+1)}>Refresh</Action></div>
  {!data&&!error?<p role="status" className="st-loading">Loading tracked orders…</p>:data?.rows.length?<div className="st-table-wrap"><table className="st-table"><thead><tr>{['Order','Campaign','Salesman','Mode','Sale','Commission','Status','Date'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.rows.map((r:any)=>{const complete=['auto_posted','test_calculated'].includes(r.status);return <tr key={r.id}><td><strong>{r.customer_name||'Checkout order'}</strong><small className="st-block">{r.order_id}</small></td><td>{r.campaign_name}</td><td>{r.salesperson_name}</td><td><span className="st-muted">{r.mode==='test'?'Test purchase':r.mode==='live'?'Live purchase':'Verifying mode'}</span></td><td>{complete?money(r.revenue_minor,r.currency):'Awaiting payment'}</td><td>{complete?money(r.commission_minor,r.currency):'—'}</td><td>{complete?'Tracked successfully':r.reason?'Needs attention':'Checking payment'}{r.reason&&!complete&&<details><summary>Details</summary><p className="st-help">{r.reason}</p></details>}</td><td>{new Date(r.created_at).toLocaleString(undefined,{timeZone:data.timezone,dateStyle:'medium',timeStyle:'short'})}</td></tr>;})}</tbody></table></div>:<Empty title="No tracked orders yet" description="Assign a salesman to an active campaign, copy their affiliate link, and complete a purchase. Test checkouts appear here too."/>}
  <div className="st-toolbar"><small className="st-muted">Updates automatically every 15 seconds. Test orders are visible here and excluded from live earnings and payouts.</small></div>
  <Pager page={page} total={data?.total||0} limit={10} onPage={setPage}/>
 </section>;
}
