import {createContext,useContext,useEffect,useState,useRef,type ReactNode} from 'react';
import {Search,ChevronDown,Inbox,Download,Plus} from 'lucide-react';
import {trackerGet} from '../../lib/tracker-client';
export const defaults={title:'Sales Tracker',salesmanLabel:'Salesman',structureLabel:'Sales Commission Structure',payoutLabel:'Payout',mediaLabel:'Media',windowDays:'30',touch:'first',payoutTerms:'',portalMessage:''};
export function useRemote(resource:string,params:Record<string,string>={},revision=0){
 const key=JSON.stringify(params),lastKey=useRef(''),[state,setState]=useState<{data:any;loading:boolean;error:string}>({data:null,loading:true,error:''});
 useEffect(()=>{const c=new AbortController(),identity=resource+key,changed=lastKey.current!==identity;lastKey.current=identity;setState(s=>({...s,loading:changed||!s.data,error:''}));const timer=setTimeout(()=>trackerGet(resource,JSON.parse(key),c.signal).then(data=>{if(!c.signal.aborted)setState({data,loading:false,error:''});}).catch(e=>{if(!c.signal.aborted)setState({data:null,loading:false,error:e.message});}),JSON.parse(key).q?150:0);return()=>{c.abort();clearTimeout(timer);};},[resource,key,revision]);return state;
}
const PreferencesContext=createContext<{data:any;loading:boolean;error:string;values:typeof defaults}|null>(null);
export function PreferencesProvider({children}:{children:ReactNode}){const [revision,setRevision]=useState(0);useEffect(()=>{const listener=()=>setRevision(r=>r+1);window.addEventListener('tracker-preferences',listener);return()=>window.removeEventListener('tracker-preferences',listener);},[]);const result=useRemote('preferences',{},revision);return <PreferencesContext.Provider value={{...result,values:{...defaults,...result.data?.preferences}}}>{children}</PreferencesContext.Provider>;}
export function usePreferences(){const value=useContext(PreferencesContext);if(!value)throw new Error('PreferencesProvider is required.');return value;}

export function Header({title,description,children}:{title:string;description?:string;children?:ReactNode}){return <div className="st-heading"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="st-actions">{children}</div></div>;}
export function Action({children,onClick,primary=false,disabled=false,type='button'}:{children:ReactNode;onClick?:()=>void;primary?:boolean;disabled?:boolean;type?:'button'|'submit'}){return <button type={type} className={`st-button ${primary?'st-primary':''}`} disabled={disabled} onClick={onClick}>{children}</button>;}
export function AddMenu({items,label='Add'}:{items:{label:string;description?:string;onClick:()=>void}[];label?:string}){return <details className="st-menu" onKeyDown={e=>{if(e.key==='Escape')e.currentTarget.open=false;}}><summary className="st-button st-primary"><Plus size={16}/>{label}<ChevronDown size={15}/></summary><div className="st-menu-list">{items.map(item=><button key={item.label} aria-label={item.label} onClick={e=>{e.currentTarget.closest('details')!.open=false;item.onClick();}}><strong>{item.label}</strong>{item.description&&<small>{item.description}</small>}</button>)}</div></details>;}
export function Tabs({tabs,value,onChange}:{tabs:{id:string;label:string}[];value:string;onChange:(id:string)=>void}){return <nav className="st-tabs" aria-label="Section tabs">{tabs.map(t=><button key={t.id} aria-current={value===t.id?'page':undefined} onClick={()=>onChange(t.id)}>{t.label}</button>)}</nav>;}
export function SearchBox({value,onChange,placeholder='Search by name or email'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <label className="st-search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
export function Empty({title='No records yet',description='New records will appear here.',children}:{title?:string;description?:string;children?:ReactNode}){return <div className="st-empty"><div className="st-empty-icon"><Inbox size={27}/></div><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function Message({error,notice}:{error?:string;notice?:string}){return <>{error&&<div className="st-alert" role="alert">{error}</div>}{notice&&<div className="st-success" role="status">{notice}</div>}</>;}
export function Pager({total,page,limit,onPage,onLimit,loading}:{total:number;page:number;limit:number;onPage:(n:number)=>void;onLimit?:(n:number)=>void;loading?:boolean}){return <footer className="st-pagination"><span>{total?`${(page-1)*limit+1}–${Math.min(page*limit,total)} of ${total}`:'0 records'}</span><div>{onLimit&&<label>Rows per page <select value={limit} onChange={e=>onLimit(Number(e.target.value))}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label>}<Action disabled={page<=1||loading} onClick={()=>onPage(page-1)}>Previous</Action><span>{page} / {Math.max(1,Math.ceil(total/limit))}</span><Action disabled={page*limit>=total||loading} onClick={()=>onPage(page+1)}>Next</Action></div></footer>;}
export function Avatar({name}:{name:string}){return <span className="st-avatar" aria-hidden>{name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()}</span>;}
export function Badge({value}:{value:string}){return <span className={`st-badge ${['active','paid','confirmed','ready'].includes(value)?'st-green':['rejected','failed','inactive','cancelled'].includes(value)?'st-red':''}`}>{value.replace(/_/g,' ')}</span>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="st-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Steps({labels,step}:{labels:string[];step:number}){return <ol className="st-steps">{labels.map((label,i)=><li className={step>=i?'is-current':''} key={label}><b>{i+1}</b>{label}</li>)}</ol>;}
export function ExportIcon(){return <Download size={16}/>;}
export function downloadText(text:string,name:string,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function useLiveRevision(){const [revision,setRevision]=useState(0);useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')setRevision(n=>n+1);};const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[]);return [revision,()=>setRevision(n=>n+1)] as const;}
