import {useEffect,useState} from 'react';
import {Modal} from '../ui';
import {useTracker} from '../TrackerGate';
import {trackerGet,trackerPost} from '../../lib/tracker-client';
import {displayMinor} from '../../lib/exact-commission';
import {Action,Empty,Message,useRemote} from './Experience';
export default function PayoutComposer({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){
 const {workspace}=useTracker(),currency=workspace?.currency||'USD',digits=workspace?.payout_terms?.minorDigits??2;
 const [person,setPerson]=useState(''),[q,setQ]=useState(''),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const people=useRemote('people',{q,limit:'100',sort:'name'});
 useEffect(()=>{const c=new AbortController();setRows([]);setSelected([]);setError('');setLoading(false);if(!person)return;setLoading(true);(async()=>{try{let all:any[]=[];for(let page=1;page<=10;page++){const r=await trackerGet('ledger',{eligible:'1',salespersonId:person,currency,page:String(page),limit:'100'},c.signal);if(r.total>1000)throw Error('More than 1,000 eligible entries. Use the commission ledger to prepare a smaller payout.');all=all.concat(r.rows);if(all.length>=r.total)break;}if(!c.signal.aborted){setRows(all);setSelected(all.map(r=>r.id));}}catch(e){if(!c.signal.aborted)setError((e as Error).message);}finally{if(!c.signal.aborted)setLoading(false);}})();return()=>c.abort();},[person,currency]);
 const total=rows.filter(r=>selected.includes(r.id)).reduce((n,r)=>n+BigInt(r.amount_minor),0n),money=(n:string)=>displayMinor(n,currency,digits);
 return <Modal open title="Create payout" onClose={()=>{if(!busy)onClose();}} size="xl"><div className="st-dialog"><p className="st-help">Choose a salesman and review their available live commissions. Saving creates a draft; no money is sent.</p><label className="st-field"><span>Find salesman</span><input value={q} disabled={busy} onChange={e=>{setQ(e.target.value);setPerson('');}} placeholder="Search by name or email"/></label><label className="st-field"><span>Salesman</span><select disabled={busy} value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose salesman</option>{people.data?.rows.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><Message error={error||people.error}/>
 {loading?<p role="status">Checking available commissions…</p>:person&&rows.length?<><div className="st-mode-banner">Available selection <strong>{money(total.toString())}</strong> · {selected.length} entries</div><div className="st-table-wrap" style={{maxHeight:320}}><table className="st-table"><thead><tr><th>Select</th><th>Earned on</th><th>Commission</th><th>Available on</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><input type="checkbox" aria-label={`Select commission ${r.id}`} checked={selected.includes(r.id)} disabled={busy||BigInt(r.amount_minor)<0n} onChange={e=>setSelected(v=>e.target.checked?[...v,r.id]:v.filter(id=>id!==r.id))}/></td><td>{r.payment_date}</td><td>{money(String(r.amount_minor))}{BigInt(r.amount_minor)<0n&&<small className="st-block">Required refund adjustment</small>}</td><td>{r.due_date}</td></tr>)}</tbody></table></div></>:person&&!error?<Empty title="No commissions ready yet" description="Test purchases never become payable. Live commissions become available after their hold period and cannot be reserved in another payout."/>:null}
 <div className="st-dialog-footer"><Action disabled={busy} onClick={onClose}>Cancel</Action><Action primary disabled={busy||loading||!selected.length||total<=0n||!!error} onClick={async()=>{setBusy(true);setError('');try{await trackerPost('payout',{salespersonId:person,entryIds:selected,notes:'Created from the Payout page'});onCreated();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Saving…':'Create draft payout'}</Action></div></div></Modal>;
}
