import assert from 'node:assert/strict';
import {companyUsers,type CompanyIdentity} from '../../src/lib/company-users.js';
import {canAccess} from '../../src/lib/roles.js';
const identity=(id:string,extra:Partial<CompanyIdentity>={}):CompanyIdentity=>({id,name:id,email:`${id}@example.test`,...extra});
const external=identity('external',{provider:'ghl',external_id:'ghl-1',participant_id:'sales-1',provider_role:'admin',active:true});
const owner=identity('owner',{kleegr_user_id:'ghl-1',role:'owner',status:'active'});
const salesman=identity('sales-1',{role:'salesperson',status:'active'});
const merged=companyUsers([external],[owner],[salesman]);
assert.equal(merged.length,1);assert.equal(merged[0].login?.role,'owner');assert.equal(merged[0].salesman?.id,'sales-1');
assert.equal(companyUsers([external],[],[])[0].login,undefined);
assert.equal(companyUsers([],[],[salesman])[0].salesman?.id,'sales-1');
assert.equal(companyUsers([],[owner],[])[0].login?.role,'owner');
const local=identity('local',{email:external.email,role:'admin'});
assert.equal(companyUsers([external],[local],[])[0].matchedByEmail,true);
assert.equal(companyUsers([external],[local,{...local,id:'other'}],[]).length,3,'ambiguous email must not grant an apparent role');
assert.equal(companyUsers([external],[{...local,kleegr_user_id:'different-user'}],[]).length,2,'conflicting provider identities stay separate');
assert.equal(companyUsers([external],[{...owner,salesperson_id:'sales-1'}],[salesman]).length,1);
assert.equal(canAccess('admin','/users'),true);assert.equal(canAccess('owner','/users'),true);
for(const role of ['salesperson','affiliate','partner','accountant','sales_manager'] as const)assert.equal(canAccess(role,'/users'),false);
console.log('Company users: identity matching, independent roles/enrollment, ambiguous identity and route access checks passed.');
