import type {SessionUser} from './auth.js';
import {admin,audit,id,lock,required,workspace,TrackerError,type Database} from './tracker-common.js';
import {operationsReady} from './operations.js';
import {settlePayout} from './tracker-finance.js';
import {decimalToMinor} from '../../src/lib/exact-commission.js';
function config(tenantId:string){const mode=process.env.TRACKER_PAYPAL_MODE==='live'?'live':'sandbox';if(process.env.TRACKER_PAYPAL_TENANT_ID!==tenantId||!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)throw new TrackerError('paypal_not_configured','Connect PayPal Payouts credentials to this workspace first.',503);if(mode==='live'&&process.env.TRACKER_PAYOUTS_ENABLED!=='1')throw new TrackerError('live_payouts_disabled','Live money transfers are not activated.',409);return{mode,base:mode==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com'};}
async function token(base:string,fetchImpl:typeof fetch){const r=await fetchImpl(`${base}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${process.env.PAYPAL_CLIENT_ID}:${process.env.PAYPAL_CLIENT_SECRET}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new TrackerError('paypal_auth_failed','PayPal rejected the configured account.',502);const b:any=await r.json();if(typeof b.access_token!=='string')throw new TrackerError('paypal_auth_failed','PayPal authentication failed.',502);return b.access_token;}
function decimal(value:string){const n=BigInt(value);return`${n/100n}.${(n%100n).toString().padStart(2,'0')}`;}
export async function initiateTransfer(db:Database,u:SessionUser,b:any,fetchImpl:typeof fetch=fetch){
 admin(u);await operationsReady(db);const cfg=config(u.tenantId);const recipient=required(b.recipient,'PayPal recipient email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient))throw new TrackerError('invalid_recipient','Enter the verified PayPal recipient email.');
 if(cfg.mode==='live'&&b.confirm!=='SEND APPROVED PAYOUT')throw new TrackerError('confirmation_required','Review the recipient and type SEND APPROVED PAYOUT.');
 const access=await token(cfg.base,fetchImpl);
 const attempt=await db.transaction(async c=>{
  await lock(c,u.tenantId);
  if(cfg.mode==='sandbox'){const key=id('t').slice(0,30);await c.query("INSERT INTO tracker_transfer_attempts(id,tenant_id,mode,recipient,amount_minor,currency) VALUES($1,$2,'sandbox',$3,100,'USD')",[key,u.tenantId,recipient]);return{id:key,recipient,amount_minor:'100',currency:'USD',mode:'sandbox',payout_id:null};}
  const p=(await c.query('SELECT p.*,s.email FROM payout_batches p JOIN salespeople s ON s.tenant_id=p.tenant_id AND s.id=p.salesperson_id WHERE p.tenant_id=$1 AND p.id=$2 FOR UPDATE OF p',[u.tenantId,b.payoutId])).rows[0];
  if(!p||p.status!=='approved')throw new TrackerError('approved_payout_required','Choose a separately approved payout.');
  if(p.email?.toLowerCase()!==recipient)throw new TrackerError('recipient_mismatch','Recipient must match the approved participant email.');
  const w=await workspace(c,u);if(Number(w.payout_terms?.minorDigits??2)!==2)throw new TrackerError('unsupported_precision','PayPal requires a workspace configured with two decimal places.');
  if(!['USD','EUR','GBP','CAD','AUD'].includes(p.currency))throw new TrackerError('unsupported_currency','This provider adapter currently supports USD, EUR, GBP, CAD and AUD.');
  if((await c.query('SELECT id FROM tracker_transfer_attempts WHERE tenant_id=$1 AND payout_id=$2',[u.tenantId,p.id])).rows.length)throw new TrackerError('attempt_exists','Reconcile the existing transfer; a second transfer cannot be created.');
  const key=id('t').slice(0,30);await c.query("INSERT INTO tracker_transfer_attempts(id,tenant_id,payout_id,mode,recipient,amount_minor,currency) VALUES($1,$2,$3,'live',$4,$5,$6)",[key,u.tenantId,p.id,recipient,p.amount_minor,p.currency]);
  await settlePayout(c,u,{id:p.id,reference:`paypal:${key}`,recipient,amountMinor:String(p.amount_minor),currency:p.currency,method:'paypal',status:'unknown',date:new Date().toISOString().slice(0,10),note:'Transfer reserved before provider submission. Reconcile provider status before any further payment.'});
  return{id:key,recipient,amount_minor:String(p.amount_minor),currency:p.currency,mode:'live',payout_id:p.id};
 });
 try{const r=await fetchImpl(`${cfg.base}/v1/payments/payouts`,{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json','PayPal-Request-Id':attempt.id},body:JSON.stringify({sender_batch_header:{sender_batch_id:attempt.id,email_subject:'Your sales commission payout'},items:[{recipient_type:'EMAIL',receiver:recipient,amount:{value:decimal(attempt.amount_minor),currency:attempt.currency},sender_item_id:attempt.id}]}),redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('provider_not_confirmed');const result:any=await r.json();const batch=result.batch_header?.payout_batch_id;if(typeof batch!=='string')throw new Error('invalid_response');await db.query("UPDATE tracker_transfer_attempts SET provider_batch_id=$2,status='processing' WHERE id=$1",[attempt.id,batch]);return{id:attempt.id,mode:cfg.mode,status:'processing',moneyConfirmed:false};}
 catch{throw new TrackerError('transfer_unknown','PayPal submission was not confirmed. The attempt is saved; reconcile it before another payment.',502);}
}
export async function reconcileTransfer(db:Database,u:SessionUser,b:any,fetchImpl:typeof fetch=fetch){
 admin(u);await operationsReady(db);const cfg=config(u.tenantId),a=(await db.query('SELECT * FROM tracker_transfer_attempts WHERE tenant_id=$1 AND id=$2',[u.tenantId,b.id])).rows[0];if(!a||a.mode!==cfg.mode)throw new TrackerError('not_found','Transfer not found in the configured provider mode.',404);if(a.status==='confirmed')return{duplicate:true};
 const batch=required(a.provider_batch_id||b.providerBatchId,'PayPal batch ID',100);if(!/^[a-zA-Z0-9]+$/.test(batch))throw new TrackerError('invalid_reference','Invalid PayPal batch ID.');const access=await token(cfg.base,fetchImpl),r=await fetchImpl(`${cfg.base}/v1/payments/payouts/${batch}?page_size=10`,{headers:{Authorization:`Bearer ${access}`},redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new TrackerError('provider_unavailable','PayPal status could not be checked.',502);const result:any=await r.json();
 const items=result.items;if(result.batch_header?.sender_batch_header?.sender_batch_id!==a.id||!Array.isArray(items)||items.length!==1)throw new TrackerError('reference_mismatch','Provider batch does not match this exact transfer.');
 const item=items[0],p=item.payout_item;if(p?.sender_item_id!==a.id||p?.receiver?.toLowerCase()!==a.recipient||p?.amount?.currency!==a.currency||decimalToMinor(String(p?.amount?.value),2)!==String(a.amount_minor))throw new TrackerError('transfer_mismatch','Provider recipient or amount differs from the approved transfer.');
 if(item.transaction_status!=='SUCCESS')return{status:item.transaction_status||'unknown',moneyConfirmed:false};
 return db.transaction(async c=>{const current=(await c.query('SELECT status FROM tracker_transfer_attempts WHERE id=$1 FOR UPDATE',[a.id])).rows[0];if(current.status==='confirmed')return{duplicate:true};
  if(a.mode==='live')await settlePayout(c,u,{id:a.payout_id,reference:`paypal:${a.id}`,recipient:a.recipient,amountMinor:String(a.amount_minor),method:'paypal',status:'confirmed',date:new Date().toISOString().slice(0,10),reconciliationReason:`PayPal verified item ${item.payout_item_id}; transaction ${item.transaction_id}.`});
  await c.query("UPDATE tracker_transfer_attempts SET status='confirmed',provider_batch_id=$2,confirmed_at=now() WHERE id=$1",[a.id,batch]);await audit(c,u,'transfer',a.id,'provider_confirmed',{mode:a.mode,providerBatchId:batch});return{status:'confirmed',mode:a.mode,moneyConfirmed:a.mode==='live'};});
}
