import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Wallet,Users,TrendingUp,ArrowUpRight,Coins} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {useTracker} from '../../components/TrackerGate';
import {displayMinor} from '../../lib/exact-commission';
import {trackerCSV} from '../../lib/tracker-client';
import {Action,Avatar,Badge,Empty,ExportIcon,Header,Message,Pager,SearchBox,Tabs,useRemote} from '../../components/tracker/Experience';
export default function TrackerDashboard(){
 const {workspace}=useTracker(),currency=workspace?.currency||'USD',digits=workspace?.payout_terms?.minorDigits??2;
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[campaignId,setCampaign]=useState(''),[tab,setTab]=useState('ledger'),[q,setQ]=useState(''),[page,setPage]=useState(1),[error,setError]=useState('');
 const state=useRemote('overview',{from,to,campaignId}),campaigns=useRemote('campaigns',{limit:'100'}),latest=useRemote(tab,{q,from,to,campaignId,page:String(page),limit:'10',sort:'recent',direction:'desc'});
 const r=state.data,money=(v:string)=>displayMinor(v||'0',currency,digits),cash=r?.receipts.find((x:any)=>x.currency===currency),earnings=r?.earnings.find((x:any)=>x.currency===currency);
 const top=[...(r?.performance||[])].sort((a:any,b:any)=>{const x=BigInt(a.revenue.find((v:any)=>v.currency===currency)?.amount||'0'),y=BigInt(b.revenue.find((v:any)=>v.currency===currency)?.amount||'0');return x===y?Number(b.generated)-Number(a.generated):x>y?-1:1;}).slice(0,5);
 const trend=(r?.trend||[]).filter((x:any)=>x.currency===currency).map((x:any)=>({...x,amount:Number(x.amount_minor)/10**digits}));
 return <div className="st-page"><Header title="Dashboard" description="Track revenue, sales performance and commissions."><label className="st-date"><span>From</span><input aria-label="Dashboard from date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="st-date"><span>To</span><input aria-label="Dashboard to date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><select className="st-select" aria-label="Dashboard structure" value={campaignId} onChange={e=>setCampaign(e.target.value)}><option value="">All Sales Commission Structures</option>{campaigns.data?.rows.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Header>
 <Message error={state.error||latest.error||error}/>{!workspace&&<div className="st-setup-banner"><div><strong>Finish your workspace setup</strong><p>Confirm currency and timezone before adding commission structures or recording payments.</p></div><Link className="st-button st-primary" to="/tracker-settings">Complete setup<ArrowUpRight size={16}/></Link></div>}
 {state.loading?<div role="status" className="st-loading">Loading dashboard…</div>:r&&<><div className="st-stats"><div className="st-stat"><span className="st-stat-icon"><Wallet size={21}/></span><p>Total revenue generated</p><strong>{money(cash?.net_collected_minor)}</strong><small>Confirmed receipts after refunds · {currency}</small></div><div className="st-stat"><span className="st-stat-icon"><TrendingUp size={21}/></span><p>Conversion rate</p><strong>{Number(r.cohort.leads)?(Number(r.cohort.customers)/Number(r.cohort.leads)*100).toFixed(1):'0'}%</strong><small>Contacts in this period who became customers</small></div><div className="st-stat"><span className="st-stat-icon"><Users size={21}/></span><p>Total customers</p><strong>{r.cohort.customers}</strong><small>{r.cohort.leads} contacts · {r.salesmen} salesmen</small></div></div>
 <div className="st-dashboard-grid"><section className="st-panel"><div className="st-panel-heading"><h2>Overview</h2><span className="st-chart-legend">● Revenue · {currency}</span></div>{trend.length?<div className="st-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:15,right:25,left:15,bottom:10}}><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.18}/><stop offset="100%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7ebf0"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip formatter={(_v:any,_n:any,p:any)=>money(p.payload.amount_minor)}/><Area type="monotone" dataKey="amount" stroke="#2563eb" fill="url(#revenue-fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>:<Empty title="Revenue will appear here" description="Your chart updates when confirmed receipts are recorded."/>}</section>
 <section className="st-panel"><div className="st-panel-heading"><h2>Top Salesmen</h2><span className="st-muted">By revenue</span></div>{top.length?<div className="st-leaderboard">{top.map((p:any,i:number)=><div key={p.id}><span className="st-rank">{i+1}</span><Avatar name={p.name}/><div><strong>{p.name}</strong><small>{p.generated} leads generated · {p.assigned} assigned</small></div><b>{money(p.revenue.find((v:any)=>v.currency===currency)?.amount)}</b></div>)}</div>:<Empty title="Your team performance" description="Add salesmen to start tracking their results."/>}<Link to="/people" className="st-panel-link">View all salesmen <ArrowUpRight size={15}/></Link></section></div>
 <div className="st-stats st-stats-four">{[['Commission earned',earnings?.earned_minor,'/ledger'],['Ready for payout',earnings?.payable_minor,'/ledger'],['On hold',earnings?.held_minor,'/ledger'],['Commission paid',earnings?.paid_minor,'/payouts']].map(([label,value,url])=><Link key={label} to={url!} className="st-stat st-small-stat"><p>{label}<Coins size={17}/></p><strong>{money(value)}</strong></Link>)}</div>
 {r.attention&&<div className="st-attention"><Link to="/payouts">Pending payout approvals <b>{r.attention.pending_approvals}</b></Link><Link to="/sync-review">Imports to review <b>{r.attention.pending_imports}</b></Link><Link to="/clients">Attribution reviews <b>{r.attention.attribution_conflicts}</b></Link></div>}
 <section className="st-panel"><Tabs value={tab} onChange={v=>{setTab(v);setPage(1);setQ('');}} tabs={[{id:'ledger',label:'Latest Commissions'},{id:'people',label:'Latest Salesmen'}]}/><div className="st-toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder={tab==='people'?'Search salesman name or email':'Search commission records'}/><Action onClick={()=>void trackerCSV(tab,{q,from,to,campaignId}).catch(e=>setError(e.message))}><ExportIcon/>Export CSV</Action></div>{latest.loading?<p className="st-loading" role="status">Loading records…</p>:latest.data?.rows.length?<div className="st-table-wrap"><table className="st-table"><thead><tr>{(tab==='people'?['Name','Email','Role','Status']:['Salesman','Amount','Status','Date','Description']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{latest.data.rows.map((x:any)=><tr key={x.id}>{tab==='people'?<><td>{x.name}</td><td>{x.email}</td><td>{x.role}</td><td><Badge value={x.status}/></td></>:<><td>{x.salesperson_name||'Unassigned'}</td><td>{x.amount_minor!=null?displayMinor(String(x.amount_minor),x.currency,digits):'Earlier record'}</td><td><Badge value={x.status}/></td><td>{x.payment_date}</td><td className="st-wrap">{x.explanation||'—'}</td></>}</tr>)}</tbody></table></div>:<Empty title="No matching records" description="Try another date range or add your first record."/>}<Pager total={latest.data?.total||0} page={page} limit={10} onPage={setPage}/></section>
 <details className="st-disclosure"><summary>How these numbers are calculated</summary>{Object.values(r.definitions).map((text:any,i)=><p key={i} className="st-help">{text}</p>)}{r.receipts.some((x:any)=>x.currency!==currency)&&<p className="st-help">Additional currencies are available in Reports. Dashboard cards use {currency}.</p>}</details></>}
 </div>;
}
