import {useState} from 'react';
import {Folder,FileText,Plus,LayoutGrid,List,Upload,Link as LinkIcon} from 'lucide-react';
import {Modal} from '../../components/ui';
import {useAuth} from '../../store/AuthContext';
import {trackerPost} from '../../lib/tracker-client';
import {Action,Empty,Field,Header,Message,Pager,SearchBox,useRemote,usePreferences} from '../../components/tracker/Experience';
export default function Media(){
 const {user}=useAuth(),admin=['owner','admin'].includes(user?.role||''),pref=usePreferences();
 const [q,setQ]=useState(''),[folderId,setFolder]=useState(''),[campaignId,setCampaign]=useState(''),[view,setView]=useState('grid'),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[dialog,setDialog]=useState(''),[b,setB]=useState<any>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[kind,setKind]=useState('file');
 const files=useRemote('media',{q,folderId,campaignId,page:String(page),limit:'12'},revision),folders=useRemote('folders',{},revision),campaigns=useRemote('campaigns',{limit:'100'});
 const open=(type:string)=>{setDialog(type);setB({folderId,campaignId,audience:'participants'});setError('');};
 async function read(file?:File){if(!file)return;setError('');try{if(file.size>2000000)throw new Error('Choose a file of 2 MB or smaller.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));setB((v:any)=>({...v,base64:btoa(binary),mime:file.type,fileName:file.name,title:v.title||file.name}));}catch(e){setError((e as Error).message);}}
 return <div className="st-page"><Header title={pref.values.mediaLabel} description="Organize the resources your salesmen need.">{admin&&<><Action onClick={()=>open('folder')}><Folder size={16}/>Create Folder</Action><Action primary onClick={()=>open('file')}><Plus size={16}/>Add File</Action></>}</Header><Message error={files.error||folders.error||(!dialog?error:'')} notice={notice}/><section className="st-panel"><div className="st-toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder="Search file or folder name"/><div className="st-actions"><select className="st-select" aria-label="Media structure" value={campaignId} onChange={e=>{setCampaign(e.target.value);setPage(1);}}><option value="">All Structures</option>{campaigns.data?.rows.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Action onClick={()=>setView(view==='grid'?'list':'grid')}>{view==='grid'?<List size={16}/>:<LayoutGrid size={16}/>} {view==='grid'?'List':'Grid'}</Action></div></div>
 {folderId&&<div className="st-toolbar"><Action onClick={()=>{setFolder('');setPage(1);}}>← All media</Action><strong>{folders.data?.rows.find((f:any)=>f.id===folderId)?.name}</strong></div>}
 {!folderId&&folders.data?.rows.length>0&&<div className="st-media-grid">{folders.data.rows.filter((f:any)=>f.name.toLowerCase().includes(q.toLowerCase())).map((f:any)=><button key={f.id} className="st-choice" onClick={()=>{setFolder(f.id);setQ('');setPage(1);}}><Folder size={28} color="#e6ad3a"/><strong>{f.name}</strong></button>)}</div>}
 {files.loading?<p className="st-loading" role="status">Loading media…</p>:files.data?.rows.length?<div className={view==='grid'?'st-media-grid':'st-table-wrap'}>{view==='grid'?files.data.rows.map((f:any)=><a key={f.id} href={f.url} target="_blank" rel="noreferrer" className="st-media-card"><div className="st-media-preview"><FileText size={44}/></div><div><strong>{f.title}</strong><small>{f.description||'Shared resource'}</small><small className="st-block">{f.audience==='admin'?'Administrators only':'Available to participants'}</small></div></a>):<table className="st-table"><thead><tr><th>Name</th><th>Description</th><th>Shared with</th><th></th></tr></thead><tbody>{files.data.rows.map((f:any)=><tr key={f.id}><td>{f.title}</td><td>{f.description}</td><td>{f.audience}</td><td><a className="st-text-link" href={f.url} target="_blank" rel="noreferrer">Open file</a></td></tr>)}</tbody></table>}</div>:<Empty title={folderId?'This folder is empty':'No files yet'} description="Upload a file or add a resource link to share with your team.">{admin&&<Action primary onClick={()=>open('file')}>Add File</Action>}</Empty>}<Pager total={files.data?.total||0} page={page} limit={12} onPage={setPage}/></section>
 {dialog&&<Modal open title={dialog==='folder'?'Create Folder':'New Upload'} size="lg" onClose={()=>{if(!busy)setDialog('');}}><form className="st-dialog" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await trackerPost(dialog==='folder'?'mediaFolder':'mediaFile',dialog==='folder'?b:{...b,...(kind==='link'?{base64:undefined}:{url:undefined})});setDialog('');setNotice(dialog==='folder'?'Folder created.':'Resource saved.');setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{dialog==='folder'?<Field label="Folder name *"><input required value={b.name||''} onChange={e=>setB({...b,name:e.target.value})}/></Field>:<><div className="st-actions"><Action onClick={()=>setKind('file')}><Upload size={15}/>Upload file</Action><Action onClick={()=>setKind('link')}><LinkIcon size={15}/>Resource link</Action></div>{kind==='file'?<label className="st-dropzone"><Upload size={28}/><strong>{b.fileName||'Choose your file'}</strong><span>PDF, PNG, JPG, WebP · Maximum 2 MB</span><input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" required={!b.base64} onChange={e=>void read(e.target.files?.[0])}/></label>:<Field label="Resource URL *"><input type="url" required value={b.url||''} onChange={e=>setB({...b,url:e.target.value})}/></Field>}<Field label="Title *"><input required value={b.title||''} onChange={e=>setB({...b,title:e.target.value})}/></Field><Field label="Description"><textarea value={b.description||''} onChange={e=>setB({...b,description:e.target.value})}/></Field><div className="st-form-grid"><Field label="Folder"><select value={b.folderId||''} onChange={e=>setB({...b,folderId:e.target.value})}><option value="">All media</option>{folders.data?.rows.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Field label="Sales Commission Structure"><select value={b.campaignId||''} onChange={e=>setB({...b,campaignId:e.target.value})}><option value="">Share across this workspace</option>{campaigns.data?.rows.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Audience"><select value={b.audience} onChange={e=>setB({...b,audience:e.target.value})}><option value="participants">Participants</option><option value="admin">Administrators only</option></select></Field></div></>}<Message error={error}/><div className="st-dialog-footer"><Action disabled={busy} onClick={()=>setDialog('')}>Cancel</Action><Action primary type="submit" disabled={busy}>{busy?'Saving…':dialog==='folder'?'Create Folder':'Save File'}</Action></div></form></Modal>}</div>;
}
