import {decimalToMinor,displayMinor} from '../../lib/exact-commission';
import {Reference} from '../../components/TrackerForm';

import {useEffect,useState} from 'react';

import {Link} from 'react-router-dom';

import {Header,Action,Field,Message} from '../../components/tracker/Experience';

import {trackerGet} from '../../lib/tracker-client';



async function api(resource:string){const r=await fetch(`/api/operations?${resource}`);const b=await r.json();if(!r.ok)throw new Error(b.message||b.error);return b;}

async function post(action:string,data:any){const r=await fetch('/api/operations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,data})});const b=await r.json();if(!r.ok)throw new Error(b.message||b.error);return b;}

async function download(resource:string,name:string){const r=await fetch(`/api/operations?${resource}`);if(!r.ok)throw new Error((await r.json()).message||'Download failed.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function Operations(){

 const [status,setStatus]=useState<any>(null),[tab,setTab]=useState('setup'),[rows,setRows]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[people,setPeople]=useState<any[]>([]),[logins,setLogins]=useState<any[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[result,setResult]=useState<any>(null),[month,setMonth]=useState(new Date().toISOString().slice(0,7));

 const [catalog,setCatalog]=useState<any>(null),[catalogKind,setCatalogKind]=useState('funnels');

 const [form,setForm]=useState<any>({kind:'funnel',name:'',url:'',campaignId:'',salespersonId:'',message:'Welcome to the team. Your administrator will share your campaign instructions and referral links.',taxKind:'W9',testAmount:'100',testRate:'10',testRefund:'20'});

 const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}));

 useEffect(()=>{let active=true;api('resource=status').then(s=>{if(active){setStatus(s);if(!s.admin)setTab(s.accountant?'reports':'tax');}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[]);

 useEffect(()=>{if(!status?.installed)return;let active=true;setError('');setRows([]);setResult(null);

 const resource:Record<string,string>={sources:'sources',inbox:'inbox',alerts:'notices',email:'emails',tax:'tax',transfers:'transfers'};

 if(resource[tab])api(`resource=${resource[tab]}`).then(b=>active&&setRows(b.rows)).catch(e=>active&&setError(e.message));

 if(tab==='churn')api(`resource=churn&month=${month}`).then(b=>active&&setResult(b)).catch(e=>active&&setError(e.message));

 if(status.admin&&['sources','email','tax','access'].includes(tab)){Promise.all([trackerGet('campaigns',{limit:'100'}),trackerGet('people',{limit:'100'}),api('resource=logins')]).then(([c,p,l])=>{if(active){setCampaigns(c.rows);setPeople(p.rows);setLogins(l.rows);}}).catch(e=>active&&setError(e.message));}

 if(tab==='setup'&&status.admin)api('resource=config').then(b=>active&&setForm((p:any)=>({...p,...b.config,stripeAccountId:b.config.stripe_account_id||'',notificationEmail:b.config.notification_email||'',notificationsEnabled:b.config.notifications_enabled===true}))).catch(e=>active&&setError(e.message));

 return()=>{active=false;};},[tab,status,revision,month]);

 async function run(action:string,data:any){setBusy(true);setError('');setNotice('');try{const r=await post(action,data);if(action!=='testScenario')setRevision(n=>n+1);setNotice(action==='testScenario'?'Test completed; no records saved.':['initiateTransfer','reconcileTransfer'].includes(action)?`Provider status: ${r.status||(r.duplicate?'already confirmed':'unknown')}. ${r.moneyConfirmed?'Payment confirmed.':'No new real payment confirmed.'}`:action==='queueWelcome'?'Welcome email queued; use Send when ready.':action==='notificationScan'?`Found ${r.created} new alerts.`:'Saved.');if(r.secret)setForm((p:any)=>({...p,newSource:r}));if(action==='testScenario')setResult(r);return r;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}

 const choose=(key:string,label:string,options:any[])=> <Field label={label}><select required value={form[key]||''} onChange={e=>set(key,e.target.value)}><option value="">Choose…</option>{options.map(p=><option key={p.id} value={p.id}>{p.name||p.email||p.id}</option>)}</select></Field>;

 const field=(key:string,label:string,type='text',extra:any={})=><Field label={label}><input required type={type} value={form[key]||''} onChange={e=>set(key,e.target.value)} {...extra}/></Field>;

 if(!status)return <p role="status">Loading connected operations… {error}</p>;

 const tabs=status.admin?[['setup','Connections'],['sources','Funnels & websites'],['inbox','Event inbox'],['transfers','Provider payouts'],['alerts','Alerts'],['email','Welcome emails'],['tax','Tax forms'],['reports','Monthly exports'],['churn','Subscription churn'],['access','Accountant access'],['test','Free test lab']]:status.accountant?[['reports','Monthly exports']]:[['tax','My tax forms']];

 return <div className="st-page"><Header title="Connected operations" description="Connect your sales sources, verify events and manage the work around commissions."/><Message error={error} notice={notice}/>{!status.installed?<div className="st-panel"><h2>Database activation required</h2><p>The reviewed connected-operations migration must be applied before these features can save data.</p></div>:<><nav className="st-tabs" aria-label="Operations sections">{tabs.map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setNotice('');setResult(null);}}>{label}</button>)}</nav><section className="st-panel st-settings-content">

 {tab==='setup'&&<><h2>Connection status</h2><div className="st-table-scroll"><table className="st-table"><thead><tr><th>Service</th><th>Current configuration</th></tr></thead><tbody>{[['Stripe credentials',status.stripe],['Stripe signed events',status.stripeWebhook],['Email sender',status.email],['Email sending activated',status.emailEnabled],['Encrypted tax storage',status.taxEncryption],['Kleegr read gateway',status.gateway]].map(([name,ready])=><tr key={String(name)}><td>{name}</td><td>{ready?'Configured — verify the complete flow':'Needs configuration'}</td></tr>)}</tbody></table></div><p className="st-help">Configuration is not proof of a completed test. Source verification and received events appear in their own tabs. PayPal Payouts has a separate sandbox/live activation. A test transfer never settles real earnings.</p><form onSubmit={e=>{e.preventDefault();void run('providerConfig',{stripeAccountId:form.stripeAccountId,notificationEmail:form.notificationEmail,notificationsEnabled:form.notificationsEnabled===true});}}>{field('stripeAccountId','Stripe account ID','text',{required:false,placeholder:'acct_…'})}{field('notificationEmail','Operations email','email',{required:false})}<label><input type="checkbox" checked={form.notificationsEnabled===true} onChange={e=>set('notificationsEnabled',e.target.checked)}/> Enable daily operational digests and welcome emails for future enrollments</label><Action primary type="submit" disabled={busy}>Verify and save connection</Action></form><p className="st-help">Stripe account ownership is checked against server credentials. Register {window.location.origin}/api/stripe-events for charge.succeeded, refund.created, refund.updated and customer.subscription created/updated/deleted events. Keep test and live records separate.</p><Link className="st-text-link" to="/tracker-settings">Configure workspace currency and timezone</Link></>}

 {tab==='sources'&&<><h2>Connect a funnel, website or booking source</h2><div className="st-disclosure"><Field label="Browse connected GHL assets"><select value={catalogKind} onChange={e=>{setCatalogKind(e.target.value);setCatalog(null);}}>{['funnels','forms','surveys','calendars'].map(k=><option key={k}>{k}</option>)}</select></Field><Action disabled={busy||!status.gateway} onClick={async()=>{setBusy(true);try{setCatalog(await api(`resource=catalog&kind=${catalogKind}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Load from GHL</Action>{!status.gateway&&<p>Activate the Kleegr read gateway to browse assets.</p>}{catalog&&<><p>Page {catalog.page}</p>{catalog.rows.map((r:any)=><p key={r.id}>{r.name} <Action onClick={()=>{set('name',r.name);set('kind',catalogKind==='funnels'?'funnel':catalogKind==='forms'?'form':catalogKind==='surveys'?'survey':'calendar');if(r.url)set('url',r.url);}}>Use this asset</Action></p>)}{catalog.hasMore&&<Action onClick={async()=>{try{setCatalog(await api(`resource=catalog&kind=${catalogKind}&page=${catalog.page+1}`));}catch(e){setError((e as Error).message);}}}>Next page</Action>}</>}</div><p className="st-help">Use an external campaign on the same domain. A signed server/workflow event links the original referral to your local client. Adding an iframe alone does not verify conversion tracking.</p><form onSubmit={e=>{e.preventDefault();void run('createSource',form);}}>{field('name','Connection name')}{choose('campaignId','External campaign',campaigns.filter(c=>c.conversion_mode==='external'))}<Field label="Source type"><select value={form.kind} onChange={e=>set('kind',e.target.value)}>{['funnel','website','store','form','survey','calendar'].map(k=><option key={k}>{k}</option>)}</select></Field>{field('url','Published page URL','url')}<Action primary type="submit" disabled={busy}>Create connection</Action></form>{form.newSource&&<div className="st-disclosure"><h3>Install this connection</h3><p>Copy this credential into your server or GHL workflow Authorization header. It is shown only now; never put it in page JavaScript or a public URL.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>POST {window.location.origin}/api/source-event?source={form.newSource.id}{'\n'}Authorization: Bearer {form.newSource.secret}{'\n'}Content-Type: application/json</pre><p>Send this verification event first:</p><pre>{JSON.stringify({eventId:'connection-check-1',kind:'verification',test:true},null,2)}</pre><Action onClick={()=>set('newSource',null)}>I have saved the credential</Action></div>}

 <h3>Capture the referral identifier</h3><p className="st-help">Your affiliate link adds referralClick to the destination URL. Save that value in a hidden field on your form and include it in your trusted workflow event. For embedded GHL forms/calendars, explicitly configure the matching custom field; the outer page cannot read a third-party iframe.</p><pre style={{whiteSpace:'pre-wrap'}}>{`const click = new URL(location.href).searchParams.get('referralClick');\n// Map this value to your form's hidden referral field.\n// Send it as clickId from the authenticated server/workflow.`}</pre><details><summary>Example lead event</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify({eventId:'unique-form-submission-id',kind:'lead',test:true,clickId:'captured-referralClick',name:'Test Customer',email:'your-test-email',consent:true},null,2)}</pre><p>For a live submission, set test to false only after testing. Payment events also require amountMinor, currency, date, productId, provider, providerAccount and paymentReference. Source events enter review; page JavaScript cannot create a payable commission.</p></details>

 {rows.map(r=><article className="st-disclosure" key={r.id}><strong>{r.name}</strong><p>{r.kind} · {r.status}</p><a className="st-text-link" href={r.url} target="_blank" rel="noreferrer">Open published page</a><details><summary>Embed example</summary><pre style={{whiteSpace:'pre-wrap'}}>{`<iframe src="${r.url}" title="${r.kind}" width="100%" height="700"></iframe>`}</pre><p>Embedding depends on the source's framing policy. Verify the full referral path after installation.</p></details><Action disabled={busy} onClick={()=>{if(confirm('Replace this source credential? Existing workflows will need the new credential.'))void run('rotateSource',{id:r.id});}}>Replace credential</Action></article>)}</>}

 {tab==='inbox'&&<><h2>Verified delivery, reviewed attribution</h2><p className="st-help">Test events are visible here but cannot become real earnings. For a live event, match the local client and review the evidence. First review the referral lead, then its payment.</p>{rows.length===0&&<p>No source events received yet. Install and verify a connection first.</p>}{rows.map(r=><article className="st-disclosure" key={r.id}><strong>{r.kind} · {r.status}</strong><p>{r.provider} · {r.external_id}</p><details><summary>Event details</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(r.payload,null,2)}</pre></details>{r.status==='pending'&&<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run('reviewEvent',{id:r.id,clientId:form['client-'+r.id],productId:data.get('productId'),reason:data.get('reason'),confirmMapping:data.get('mapping')==='on'});}}><Field label="Matched local client ID"><input name="clientId" required placeholder="Copy the ID from Clients → Details"/></Field><Field label="Product mapping"><input name="productId"/></Field><Field label="Review evidence"><input name="reason" required/></Field><label><input type="checkbox" name="mapping"/> I verified the payment account, charge ID, minor currency units and product.</label><div className="st-dialog-footer"><Action disabled={busy} onClick={()=>{const reason=prompt('Reason for rejecting this event');if(reason)void run('reviewEvent',{id:r.id,reject:true,reason});}}>Reject</Action><Action primary disabled={busy} type="submit">Approve reviewed event</Action></div></form>}</article>)}</>}

 {tab==='transfers'&&<><h2>PayPal Payouts</h2><p>Mode: <strong>{status.payoutMode}</strong> · {status.paypal?'Credentials configured':'Provider account not connected'}</p><p className="st-help">Sandbox sends a simulated $1 payout to a PayPal sandbox recipient. It never marks a real commission paid. Live mode requires server activation and an approved payout; the recipient must match the participant email.</p><form onSubmit={e=>{e.preventDefault();void run('initiateTransfer',{recipient:form.recipient,payoutId:form.payoutId,confirm:form.transferConfirm});}}>{field('recipient','PayPal recipient email','email')}{status.payoutMode==='live'&&<><Field label="Approved payout"><Reference field={{key:'payout',label:'Approved payout',resource:'payouts'}} value={form.payoutId} onChange={v=>set('payoutId',v)}/></Field>{field('transferConfirm','Type SEND APPROVED PAYOUT to confirm')}</>}<Action primary type="submit" disabled={busy||!status.paypal||(status.payoutMode==='live'&&!status.livePayouts)}>{status.payoutMode==='live'?'Send approved payout':'Send $1 sandbox test'}</Action></form>{rows.map(r=><article className="st-disclosure" key={r.id}><strong>{r.mode} · {r.status}</strong><p>{r.recipient} · {r.amount_minor} minor units {r.currency}</p><p>Provider reference: {r.provider_batch_id||'Unknown — find the matching sender batch in PayPal'}</p>{r.status!=='confirmed'&&<Action disabled={busy||!status.paypal} onClick={()=>{const providerBatchId=r.provider_batch_id||prompt('PayPal batch ID from the provider dashboard');if(providerBatchId)void run('reconcileTransfer',{id:r.id,providerBatchId});}}>Check provider and reconcile</Action>}</article>)}</>}

 {tab==='alerts'&&<><h2>Operational alerts</h2><Action primary disabled={busy} onClick={()=>void run('notificationScan',{})}>Check for alerts</Action><p className="st-help">Checks pending approvals, eligible commissions, failed syncs and source events awaiting review. Repeated checks do not duplicate alerts.</p>{rows.map(r=><article className="st-disclosure" key={r.id}><strong>{r.title}</strong><p>{r.body}</p>{!r.read_at&&<Action disabled={busy} onClick={()=>void run('readNotice',{id:r.id})}>Mark read</Action>}</article>)}</>}

 {tab==='email'&&<><h2>Welcome emails</h2><p className="st-help">Queue a welcome for an enrolled salesperson, review it, then send through your configured email provider. No login is created by sending a welcome.</p><form onSubmit={e=>{e.preventDefault();void run('queueWelcome',form);}}>{choose('salespersonId','Salesperson',people)}<Field label="Welcome message"><textarea required maxLength={3000} value={form.message} onChange={e=>set('message',e.target.value)}/></Field><Action primary disabled={busy} type="submit">Queue welcome</Action></form>{rows.map(r=><article className="st-disclosure" key={r.id}><strong>{r.subject} · {r.status}</strong><p>{r.recipient}</p><pre style={{whiteSpace:'pre-wrap'}}>{r.body}</pre>{r.last_error&&<p>{r.last_error}</p>}{r.status==='pending'&&<Action disabled={busy||!status.emailEnabled} onClick={()=>{if(confirm(`Send this welcome email to ${r.recipient}?`))void run('sendEmail',{id:r.id});}}>Send email</Action>}</article>)}</>}

 {tab==='tax'&&<><h2>Private tax forms</h2><p className="st-help">Upload a completed PDF. Documents are encrypted and available only to the participant and administrators. Acceptance records administrative review; it does not certify tax compliance.</p>{!status.taxEncryption?<p role="status">An administrator must configure the encryption key before uploads are enabled.</p>:<form onSubmit={async e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('pdf') as HTMLInputElement;const file=input.files?.[0];if(!file)return;if(file.size>2000000){setError('PDF must be no larger than 2 MB.');return;}const reader=new FileReader();reader.onload=()=>void run('submitTax',{salespersonId:status.admin?form.salespersonId:status.participantId,kind:form.taxKind,filename:file.name,content:String(reader.result).split(',')[1]});reader.readAsDataURL(file);}}>{status.admin&&choose('salespersonId','Participant',people)}<Field label="Form type"><select value={form.taxKind} onChange={e=>set('taxKind',e.target.value)}><option value="W9">W-9</option><option value="W8BEN">W-8BEN</option><option value="W8BENE">W-8BEN-E</option></select></Field><Field label="Completed PDF (maximum 2 MB)"><input type="file" name="pdf" accept="application/pdf" required/></Field><Action primary type="submit" disabled={busy}>Upload securely</Action></form>}{rows.map(r=><article className="st-disclosure" key={r.id}><strong>{r.kind} · {r.status}</strong><p>{r.filename} · {r.review_note}</p><Action onClick={()=>void download(`resource=taxFile&id=${encodeURIComponent(r.id)}`,r.filename).catch(e=>setError(e.message))}>Download</Action>{status.admin&&r.status==='submitted'&&['accepted','rejected'].map(state=><Action key={state} disabled={busy} onClick={()=>{const reason=prompt('Review note');if(reason)void run('reviewTax',{id:r.id,status:state,reason});}}>{state==='accepted'?'Accept':'Reject'}</Action>)}</article>)}</>}

 {tab==='reports'&&<><h2>Monthly report package</h2><p className="st-help">Download one ZIP containing a PDF summary, receipts CSV, earnings CSV, settlements CSV and metric definitions. Currency totals remain separate; forecasts are excluded.</p><Field label="Report month"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field><Action primary disabled={busy} onClick={async()=>{setBusy(true);try{await download(`resource=package&month=${month}`,`sales-tracker-${month}.zip`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Download PDF + CSV package</Action></>}

 {tab==='churn'&&<><h2>Measured subscription churn</h2><Field label="Month"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field>{result&&<><p>{result.tracked_subscriptions} live subscriptions tracked</p><p>Active at month start: {result.starting_subscriptions}</p><p>Cancelled from that starting group: {result.cancelled_from_starting_cohort}</p><strong>{result.rate===null?'Not enough data':`${(result.rate*100).toFixed(1)}% churn`}</strong><p className="st-help">{result.definition}</p></>}</>}

 {tab==='access'&&<><h2>Read-only accountant access</h2><p className="st-help">Assign a separate existing local non-admin login to the accountant role. This replaces its previous role with read-only monthly exports; it cannot approve payouts or edit money records.</p><form onSubmit={e=>{e.preventDefault();if(confirm('Replace this login’s role with read-only accountant access?'))void run('grantAccountant',{userId:form.userId});}}>{choose('userId','Existing login',logins.filter(u=>!u.kleegr_user_id&&!['owner','admin'].includes(u.role)))}<Action primary type="submit" disabled={busy}>Assign accountant access</Action></form></>}

 {tab==='test'&&<><h2>Free commission and refund test</h2><p className="st-help">No card, provider account or charge is needed. This uses the same commission engine as real earnings and saves no people, payments or payouts.</p><form onSubmit={e=>{e.preventDefault();try{void run('testScenario',{amountMinor:decimalToMinor(form.testAmount,2),rateBps:Number(decimalToMinor(form.testRate,2)),refundMinor:decimalToMinor(form.testRefund,2)});}catch{setError('Enter valid amounts with up to two decimal places.');}}}>{field('testAmount','Payment amount (USD)','number',{min:0.01,step:0.01})}{field('testRate','Commission (%)','number',{min:0,max:100,step:0.01})}{field('testRefund','Refund amount (USD)','number',{min:0,step:0.01})}<Action primary type="submit" disabled={busy}>Run test scenario</Action></form>{result&&<div className="st-disclosure"><strong>Simulation complete — nothing posted to production</strong><ol>{result.steps.map((s:string)=><li key={s}>{s}</li>)}</ol><p>Commission: {displayMinor(result.commissionMinor,'USD',2)}</p><p>Refund adjustment: {displayMinor(result.reversalMinor,'USD',2)}</p><p>Remaining commission: {displayMinor(result.remainingCommissionMinor,'USD',2)}</p><p>{result.scope}</p></div>}</>}

 </section></>}</div>;

}
