import ImportUsers from '../../components/tracker/ImportUsers';
import {lazy} from 'react';
import SalesmanLinks from '../../components/tracker/SalesmanLinks';
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Upload,Users,UserPlus,Filter,ArrowLeft} from 'lucide-react';
import {Reference} from '../../components/TrackerForm';
import {Modal} from '../../components/ui';
import {useAuth} from '../../store/AuthContext';
import {useTracker} from '../../components/TrackerGate';
import {trackerPost,trackerCSV} from '../../lib/tracker-client';
import {displayMinor} from '../../lib/exact-commission';
import {parseSalesmanCSV} from '../../lib/salesman-csv';
import {Action,AddMenu,Avatar,Badge,Empty,ExportIcon,Field,Header,Message,Pager,SearchBox,Steps,Tabs,useRemote,usePreferences,downloadText} from '../../components/tracker/Experience';
const TrackerPage=lazy(()=>import('../TrackerPage'));

export default function Salesmen(){
 const {user}=useAuth(),admin=['admin','owner'].includes(user?.role||''),{workspace}=useTracker(),pref=usePreferences();
 const [q,setQ]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[limit,setLimit]=useState(10),[revision,setRevision]=useState(0),[section,setSection]=useState('people');
 const [dialog,setDialog]=useState<'manual'|'csv'|'contacts'|'users'|null>(null),[edit,setEdit]=useState<any>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [linkPerson,setLinkPerson]=useState<any>(null);
 const state=useRemote('salesmen',{q,status,page:String(page),limit:String(limit),sort:'name'},revision);
 const changeSearch=(v:string)=>{setQ(v);setPage(1);};
 return <div className="st-page"><Header title={pref.values.salesmanLabel} description="Only people you add or assign to campaigns appear here. Connected users are available through Add → Import from Users."><Action onClick={()=>void trackerCSV('people',{q,status}).catch(e=>setError(e.message))}><ExportIcon/>Export</Action>{admin&&<AddMenu items={[{label:'New Salesman',description:'Add a new salesman manually',onClick:()=>{setEdit(null);setDialog('manual');}},{label:'Upload Salesman',description:'Upload and map a CSV file',onClick:()=>setDialog('csv')},{label:'Import from Contacts',description:'Choose from your existing contacts',onClick:()=>setDialog('contacts')},{label:'Import from Users',description:'Choose users from this GHL sub-account',onClick:()=>setDialog('users')}]}/>}</Header>
 <Tabs value={section} onChange={setSection} tabs={[{id:'people',label:'All Salesmen'},...(admin?[{id:'directory',label:'Connected users'},{id:'teams',label:'Teams & managers'},{id:'assignments',label:'Plan assignments'}]:[])]}/>
 <Message error={error||state.error} notice={notice}/>
 {section!=='people'?<TrackerPage key={section} resource={section}/>:<section className="st-panel"><div className="st-toolbar"><SearchBox value={q} onChange={changeSearch} placeholder="Search by salesman name or email"/><label className="st-filter"><Filter size={16}/><select aria-label="Salesman status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>
 {state.loading?<div className="st-loading" role="status">Loading salesmen…</div>:state.data?.rows?.length?<div className="st-table-wrap"><table className="st-table st-salesmen-table"><thead><tr>{['Name','Sales Commission Structure','Clicks','Customers','Leads','Sub Affiliates','Owed','Paid','Revenue','Status','Actions'].map((h,i)=><th key={i} className={h==='Actions'?'st-action-cell':undefined}>{h}</th>)}</tr></thead><tbody>{state.data.rows.map((r:any)=><tr key={r.id}><td><button className="st-person" onClick={()=>{setEdit(r);setDialog('manual');}}><Avatar name={r.name}/><span><strong>{r.name}</strong><small>{r.email||'No email'}</small></span></button></td><td>{r.structures?.length?r.structures.map((c:any)=><Link className="st-text-link st-block" key={c.id} to="/campaigns">{c.name}</Link>):<span className="st-muted">Unassigned</span>}</td><td>{r.clicks||0}</td><td>{r.counts?.customers||0}</td><td>{r.counts?.leads||0}</td><td>{r.sub_affiliates||0}</td><td>{r.money?.map((m:any)=>displayMinor(m.owed,m.currency,workspace?.payout_terms?.minorDigits??2)).join(' · ')||'—'}</td><td>{r.money?.map((m:any)=>displayMinor(m.paid,m.currency,workspace?.payout_terms?.minorDigits??2)).join(' · ')||'—'}</td><td>{r.revenue?.map((m:any)=>displayMinor(m.amount,m.currency,workspace?.payout_terms?.minorDigits??2)).join(' · ')||'—'}</td><td><Badge value={r.status}/></td><td className="st-action-cell"><div className="st-row-buttons"><Action onClick={()=>setLinkPerson(r)}>Affiliate links</Action><Action onClick={()=>{setEdit(r);setDialog('manual');}}>{admin?'Manage':'View'}</Action></div></td></tr>)}</tbody></table></div>:<Empty title={q||status?'No matching salesmen':'Add your first salesman'} description="Add someone manually, upload a CSV, or choose from contacts and sub-account users.">{admin&&<Action primary onClick={()=>setDialog('manual')}><UserPlus size={16}/>New Salesman</Action>}</Empty>}
 <Pager total={state.data?.total||0} page={page} limit={limit} onPage={setPage} onLimit={n=>{setLimit(n);setPage(1);}} loading={state.loading}/></section>}
 {linkPerson&&<Modal open title={`${linkPerson.name} — Affiliate links`} size="lg" onClose={()=>setLinkPerson(null)}><SalesmanLinks salespersonId={linkPerson.id}/></Modal>}
 {dialog==='users'&&<ImportUsers onClose={()=>setDialog(null)} onSaved={n=>{setDialog(null);setNotice(`${n} users added as salesmen.`);setRevision(r=>r+1);}}/>}
 {dialog==='manual'&&<SalesmanForm person={edit} readOnly={!admin} onClose={()=>setDialog(null)} onSaved={()=>{setDialog(null);setNotice('Salesman saved.');setRevision(r=>r+1);}} onUpload={()=>setDialog('csv')}/>}
 {(dialog==='csv'||dialog==='contacts')&&<ImportSalesmen mode={dialog} onClose={()=>setDialog(null)} onSaved={n=>{setDialog(null);setNotice(`${n} salesmen added. Existing records were kept.`);setRevision(r=>r+1);}}/>}
 </div>;
}
function SalesmanForm({person,readOnly,onClose,onSaved,onUpload}:{person:any;readOnly:boolean;onClose:()=>void;onSaved:()=>void;onUpload:()=>void}){
 const names=person?.name?.split(' ')||[],[tab,setTab]=useState('basic');
 const [value,setValue]=useState<any>({firstName:names[0]||'',lastName:names.slice(1).join(' '),email:person?.email||'',phone:person?.phone||'',country:'',...person?.tracker_profile,role:person?.role||'salesperson',status:person?.status||'active',teamId:person?.team_id||'',parentId:person?.parent_salesperson_id||'',effectiveFrom:new Date().toISOString().slice(0,10)}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const plans=useRemote('plans',{limit:'100'}),teams=useRemote('teams',{limit:'100'});
 const field=(key:string,label:string,type='text',required=false)=><Field key={key} label={label}><input type={type} value={value[key]||''} required={required} disabled={readOnly||!!person?.ghl_user_id&&['firstName','lastName','email','phone'].includes(key)} onChange={e=>setValue({...value,[key]:e.target.value})}/></Field>;
 return <Modal open title={person?person.name:'New Salesman'} onClose={()=>{if(!busy)onClose();}} size="lg"><div className="st-dialog"><div className="st-toolbar"><Tabs value={tab} onChange={setTab} tabs={[{id:'basic',label:'Basic Info'},{id:'details',label:'Details'},{id:'socials',label:'Socials'}]}/>{!person&&!readOnly&&<Action onClick={onUpload}><Upload size={15}/>Upload CSV</Action>}</div>
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await trackerPost('salesman',{...value,id:person?.id});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {person?.ghl_user_id&&<p className="st-help">Name and contact information are managed by your connected CRM. Local commission roles and assignments are managed here.</p>}
 <div hidden={tab!=='basic'}><div className="st-form-grid">{field('email','Email *','email',true)}{field('company','Company name')}{field('firstName','First name *','text',true)}{field('lastName','Last name *','text',!person?.ghl_user_id)}<Field label="Commission role"><select disabled={readOnly} value={value.role} onChange={e=>setValue({...value,role:e.target.value})}><option value="salesperson">Salesman</option><option value="affiliate">Affiliate</option><option value="partner">Partner</option></select></Field><Field label="Status"><select disabled={readOnly} value={value.status} onChange={e=>setValue({...value,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></Field></div>
 {!readOnly&&<details className="st-disclosure"><summary>Commission assignment & team</summary><div className="st-form-grid"><Field label="Assign commission plan (optional)"><select value={value.versionId||''} onChange={e=>setValue({...value,versionId:e.target.value})}><option value="">Keep current assignments</option>{plans.data?.rows.map((p:any)=><option key={p.id} value={p.id}>{p.name} · Version {p.version}</option>)}</select></Field>{field('effectiveFrom','Assignment begins','date')}<Field label="Team"><select value={value.teamId} onChange={e=>setValue({...value,teamId:e.target.value})}><option value="">No team</option>{teams.data?.rows.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><div><Reference field={{key:"parentId",label:"Parent participant",resource:"people",optional:true}} value={value.parentId} onChange={v=>setValue({...value,parentId:v})}/></div></div><p className="st-help">Overlapping assignments are checked before saving. Enrollment does not create a login or send an invitation.</p></details>}</div>
 <div hidden={tab!=='details'} className="st-form-grid">{field('website','Website','url')}{field('phone','Phone','tel')}{field('companyPhone','Company phone','tel')}{field('vatId','VAT ID')}{field('country','Country')}{field('address','Address')}{field('avatar','Avatar image URL','url')}</div>
 <div hidden={tab!=='socials'} className="st-form-grid">{['facebook','x','youtube','instagram','linkedin'].map(k=>field(k,k==='x'?'X / Twitter':k[0].toUpperCase()+k.slice(1),'url'))}</div>
 <Message error={error}/><div className="st-dialog-footer"><Action disabled={busy} onClick={onClose}>{readOnly?'Close':'Cancel'}</Action>{!readOnly&&<Action primary type="submit" disabled={busy}>{busy?'Saving…':'Save Salesman'}</Action>}</div></form></div></Modal>;
}
function ImportSalesmen({mode,onClose,onSaved}:{mode:'csv'|'contacts';onClose:()=>void;onSaved:(n:number)=>void}){
 const [step,setStep]=useState(0),[csv,setCSV]=useState<string[][]>([]),[fileName,setFileName]=useState(''),[mapping,setMapping]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[review,setReview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[role,setRole]=useState('salesperson');
 const contacts=useRemote('leads',{q,page:String(page),limit:'10'});
 const rows=csv.slice(1).map(row=>Object.fromEntries(Object.entries(mapping).filter(([,i])=>i!=='').map(([k,i])=>[k,row[Number(i)]])));
 const payload=mode==='csv'?{rows,role}:{contactIds:selected,role};
 async function preview(){setBusy(true);setError('');try{setReview(await trackerPost('importSalesmen',{...payload,preview:true}));setStep(2);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function read(file?:File){if(!file)return;setError('');try{if(file.size>180000)throw new Error('Use a CSV smaller than 180 KB, with up to 500 rows.');const parsed=parseSalesmanCSV(await file.text());setCSV(parsed);setFileName(file.name);const found:Record<string,string>={};for(const [key,label] of csvFields){const index=parsed[0].findIndex(h=>[key.toLowerCase(),label.toLowerCase()].includes(h.trim().toLowerCase().replace(/_/g,' ')));found[key]=index<0?'':String(index);}setMapping(found);setStep(1);}catch(e){setError((e as Error).message);}}
 return <Modal open title={mode==='csv'?'Upload Salesman':'Import from Contacts'} size="xl" onClose={()=>{if(!busy)onClose();}}><div className="st-dialog"><Steps labels={mode==='csv'?['Upload','Map fields','Review & import']:['Select contacts','Review & import']} step={mode==='csv'?step:step===2?1:0}/><Message error={error||contacts.error}/>
 {mode==='csv'&&step===0&&<><p className="st-help">Upload your salesmen with first name, last name and email. Existing emails will be skipped.</p><label className="st-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void read(e.dataTransfer.files[0]);}}><Upload size={34}/><strong>Choose a CSV file or drag it here</strong><span>Up to 500 rows · 180 KB</span><input aria-label="Upload salesmen CSV" type="file" accept=".csv,text/csv" onChange={e=>void read(e.target.files?.[0])}/></label><Action onClick={()=>downloadText('First name,Last name,Email,Phone,Company\r\n','salesman-template.csv')}>Download sample CSV</Action></>}
 {mode==='csv'&&step===1&&<><p className="st-help">{fileName} · {csv.length-1} rows. Match your columns to these fields.</p><div className="st-form-grid">{csvFields.map(([key,label])=><Field key={key} label={`${label}${['firstName','lastName','email'].includes(key)?' *':''}`}><select value={mapping[key]||''} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Do not import</option>{csv[0].map((h,i)=><option key={i} value={i}>{h} · {csv[1]?.[i]?.slice(0,35)}</option>)}</select></Field>)}</div></>}
 {mode==='contacts'&&step!==2&&<><div className="st-toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder="Search contacts by name or email"/><span>{selected.length} selected</span></div><div className="st-table-wrap"><table className="st-table"><thead><tr><th><input aria-label="Select this page" type="checkbox" checked={!!contacts.data?.rows.length&&contacts.data.rows.every((r:any)=>selected.includes(r.id))} onChange={e=>setSelected(v=>e.target.checked?[...new Set([...v,...contacts.data.rows.map((r:any)=>r.id)])]:v.filter(id=>!contacts.data.rows.some((r:any)=>r.id===id)))}/></th><th>Name</th><th>Email</th><th>Company</th></tr></thead><tbody>{contacts.data?.rows.map((r:any)=><tr key={r.id}><td><input type="checkbox" aria-label={`Select ${r.contact_name}`} checked={selected.includes(r.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,r.id]:v.filter(id=>id!==r.id))}/></td><td>{r.contact_name}</td><td>{r.email||'No email'}</td><td>{r.company_name||'—'}</td></tr>)}</tbody></table></div>{contacts.loading&&<p role="status">Loading contacts…</p>}<Pager total={contacts.data?.total||0} page={page} limit={10} onPage={setPage}/><p className="st-help">Selection is kept when you search or change pages. Contacts stay in your client list after import.</p></>}
 {step===2&&review&&<><div className="st-import-summary"><b>{review.ready} ready to add</b><span>{review.skipped} already exist</span><span>{review.errors} need correction</span></div><div className="st-table-wrap st-review-table"><table className="st-table"><thead><tr><th>Row</th><th>Name</th><th>Email</th><th>Result</th></tr></thead><tbody>{review.rows.map((r:any)=><tr key={r.row}><td>{r.row}</td><td>{r.name}</td><td>{r.email}</td><td><Badge value={r.status}/><small className="st-block">{r.message}</small></td></tr>)}</tbody></table></div><Field label="Commission role for new salesmen"><select value={role} onChange={e=>setRole(e.target.value)}><option value="salesperson">Salesman</option><option value="affiliate">Affiliate</option><option value="partner">Partner</option></select></Field><p className="st-help">This adds commission participants. Existing records and login permissions stay intact.</p></>}
 <div className="st-dialog-footer">{step>0&&<Action disabled={busy} onClick={()=>{setStep(mode==='csv'?step-1:0);setReview(null);}}><ArrowLeft size={15}/>Back</Action>}<Action disabled={busy} onClick={onClose}>Cancel</Action>{step!==2&&(mode==='contacts'||step===1)&&<Action primary disabled={busy||(mode==='contacts'?!selected.length:['firstName','lastName','email'].some(k=>!mapping[k]))} onClick={()=>void preview()}>{busy?'Checking…':'Review import'}</Action>}{step===2&&<Action primary disabled={busy||!review?.ready||!!review?.errors} onClick={async()=>{setBusy(true);setError('');try{const result=await trackerPost('importSalesmen',payload);onSaved(result.added);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Importing…':`Import ${review?.ready||0} Salesmen`}</Action>}</div></div></Modal>;
}
const csvFields=[['firstName','First name'],['lastName','Last name'],['email','Email'],['phone','Phone'],['company','Company'],['website','Website']];
