import {useState} from 'react';
import {Link} from 'react-router-dom';
import {trackerPost} from '../../lib/tracker-client';
import {Action,Field,Header,Message,usePreferences,defaults} from '../../components/tracker/Experience';
import TrackerPage from '../TrackerPage';
export default function TrackerSettings(){
 const [tab,setTab]=useState('defaults'),pref=usePreferences(),[draft,setDraft]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const value={...pref.values,...draft},set=(k:string,v:string)=>{setDraft(d=>({...d,[k]:v}));setNotice('');};
 const labels=[{id:'defaults',label:'Default Structure Settings'},{id:'portal',label:'Affiliate Portal Settings'},{id:'custom',label:'Customizations'},{id:'accounting',label:'Currency & Payout Rules'},{id:'sync',label:'Integrations & Sync'},{id:'access',label:'Permissions & App Settings'}];
 return <div className="st-page"><Header title="Settings" description="Manage how your Sales Tracker works."/><div className="st-settings-layout"><nav className="st-settings-nav" aria-label="Settings sections">{labels.map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>{setTab(t.id);setNotice('');}}>{t.label}</button>)}</nav><section className="st-panel st-settings-content"><Message error={error||pref.error} notice={notice}/>
 {['defaults','portal','custom'].includes(tab)?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await trackerPost('preferences',draft);setDraft({});window.dispatchEvent(new Event('tracker-preferences'));setNotice('Settings saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {tab==='defaults'&&<><h2>Default Sales Commission Structure Settings</h2><p className="st-help">Applied when you create a new structure. Existing structures and earnings stay unchanged.</p><Field label="Cookie life *" hint="How long a referral remains eligible after someone opens a salesman's link."><input type="range" min="1" max="365" value={value.windowDays} onChange={e=>set('windowDays',e.target.value)}/><input type="number" min="1" max="365" required value={value.windowDays} onChange={e=>set('windowDays',e.target.value)}/><small>days</small></Field><Field label="Referral attribution"><select value={value.touch} onChange={e=>set('touch',e.target.value)}><option value="first">First referral</option><option value="last">Last referral</option></select></Field><Field label="Default payout terms"><textarea value={value.payoutTerms} onChange={e=>set('payoutTerms',e.target.value)} placeholder="Describe when salesmen can expect payment"/></Field><p className="st-help">Setup fees, recurring payments, hold periods and commission splits are configured in each structure's commission rules.</p></>}
 {tab==='portal'&&<><h2>Affiliate Portal Settings</h2><p className="st-help">Participants use their existing portal to see their referral links, performance, commissions, payouts, goals and media.</p><Field label="Portal welcome message" hint="Shown above the participant's sales summary."><textarea maxLength={1000} value={value.portalMessage} onChange={e=>set('portalMessage',e.target.value)} placeholder="Welcome to your sales portal"/></Field><div className="st-disclosure"><strong>Payout methods and notifications</strong><p className="st-help">Payments are recorded with a method and reference after they are made. Automatic transfers, welcome emails and tax-form collection need their own provider setup; they are not enabled by these settings.</p><Link className="st-text-link" to="/settings">Manage existing portal permissions</Link></div></>}
 {tab==='custom'&&<><h2>Customizations</h2><p className="st-help">Use the names your team recognizes. Changes update navigation and section headings.</p>{[['title','Title'],['salesmanLabel','Salesman'],['structureLabel','Sales Commission Structure'],['payoutLabel','Payout'],['mediaLabel','Media']].map(([key,label])=><Field key={key} label={label}><input required maxLength={60} value={value[key as keyof typeof value]} onChange={e=>set(key,e.target.value)}/></Field>)}</>}
 <div className="st-dialog-footer"><Action disabled={busy} onClick={()=>{const keys=tab==='defaults'?['windowDays','touch','payoutTerms']:tab==='portal'?['portalMessage']:['title','salesmanLabel','structureLabel','payoutLabel','mediaLabel'];setDraft(d=>({...d,...Object.fromEntries(keys.map(k=>[k,(defaults as any)[k]]))}));}}>Restore Default</Action><Action primary type="submit" disabled={busy||pref.loading}>{busy?'Saving…':'Save'}</Action></div></form>:tab==='accounting'?<TrackerPage resource="settings"/>:tab==='sync'?<TrackerPage resource="integrations"/>:<><h2>Permissions & App Settings</h2><p className="st-help">Your existing access controls, documents settings and data tools remain available.</p><Link className="st-button st-primary" to="/settings">Open App Settings</Link></>}
 </section></div></div>;
}
