import {lazy} from 'react';
import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {trackerPost} from '../../lib/tracker-client';
import {useTracker} from '../../components/TrackerGate';
import {Action,Field,Header,Message,usePreferences,useRemote,defaults} from '../../components/tracker/Experience';
const TrackerPage=lazy(()=>import('../TrackerPage'));
export default function TrackerSettings(){
 const [tab,setTab]=useState('defaults'),pref=usePreferences(),[draft,setDraft]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const value={...pref.values,...draft},set=(k:string,v:string)=>{setDraft(d=>({...d,[k]:v}));setNotice('');};
 const labels=[{id:'defaults',label:'Default Structure Settings'},{id:'pipeline',label:'Pipeline → commission'},{id:'portal',label:'Affiliate Portal Settings'},{id:'custom',label:'Customizations'},{id:'accounting',label:'Currency & Payout Rules'},{id:'sync',label:'Integrations & Sync'},{id:'access',label:'Permissions & App Settings'}];
 return <div className="st-page"><Header title="Settings" description="Manage how Kleeger works."/><Link className="st-button" to="/operations">Funnels, events, tax forms &amp; exports</Link><div className="st-settings-layout"><nav className="st-settings-nav" aria-label="Settings sections">{labels.map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>{setTab(t.id);setNotice('');}}>{t.label}</button>)}</nav><section className="st-panel st-settings-content"><Message error={error||pref.error} notice={notice}/>
 {['defaults','portal','custom'].includes(tab)?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await trackerPost('preferences',draft);setDraft({});window.dispatchEvent(new Event('tracker-preferences'));setNotice('Settings saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {tab==='defaults'&&<><h2>Default Sales Commission Structure Settings</h2><p className="st-help">Applied when you create a new structure. Existing structures and earnings stay unchanged.</p><div className="st-form-grid"><Field label="Default commission rate (%)"><input type="number" min="0" max="100" step="0.01" required value={value.commissionRate} onChange={e=>set('commissionRate',e.target.value)}/></Field><Field label="Default commission hold (days)" hint="0 makes qualifying live commissions available immediately. Test purchases never become payable."><input type="number" min="0" max="3650" step="1" required value={value.holdDays} onChange={e=>set('holdDays',e.target.value)}/></Field></div><Field label="Cookie life *" hint="How long a referral remains eligible after someone opens a salesman's link."><input type="range" min="1" max="365" value={value.windowDays} onChange={e=>set('windowDays',e.target.value)}/><input type="number" min="1" max="365" required value={value.windowDays} onChange={e=>set('windowDays',e.target.value)}/><small>days</small></Field><Field label="Referral attribution"><select value={value.touch} onChange={e=>set('touch',e.target.value)}><option value="first">First referral</option><option value="last">Last referral</option></select></Field><Field label="Default payout terms"><textarea value={value.payoutTerms} onChange={e=>set('payoutTerms',e.target.value)} placeholder="Describe when salesmen can expect payment"/></Field><p className="st-help">Setup fees, recurring payments, hold periods and commission splits are configured in each structure's commission rules.</p></>}
 {tab==='portal'&&<><h2>Affiliate Portal Settings</h2><p className="st-help">Participants use their existing portal to see their referral links, performance, commissions, payouts, goals and media.</p><Field label="Portal welcome message" hint="Shown above the participant's sales summary."><textarea maxLength={1000} value={value.portalMessage} onChange={e=>set('portalMessage',e.target.value)} placeholder="Welcome to your sales portal"/></Field><div className="st-disclosure"><strong>Payout methods and notifications</strong><p className="st-help">Payments are recorded with a method and reference after they are made. Automatic transfers, welcome emails and tax-form collection need their own provider setup; they are not enabled by these settings.</p><Link className="st-text-link" to="/settings">Manage existing portal permissions</Link></div></>}
 {tab==='custom'&&<><h2>Customizations</h2><Field label="Default dashboard view"><select value={value.dashboardMode} onChange={e=>set('dashboardMode',e.target.value)}><option value="auto">Automatic — show tests until live sales arrive</option><option value="live">Live sales</option><option value="test">Test purchases</option></select></Field><p className="st-help">Use the names your team recognizes. Changes update navigation and section headings.</p>{[['title','Title'],['salesmanLabel','Salesman'],['structureLabel','Sales Commission Structure'],['payoutLabel','Payout'],['mediaLabel','Media']].map(([key,label])=><Field key={key} label={label}><input required maxLength={60} value={value[key as keyof typeof value]} onChange={e=>set(key,e.target.value)}/></Field>)}</>}
 <div className="st-dialog-footer"><Action disabled={busy} onClick={()=>{const keys=tab==='defaults'?['commissionRate','holdDays','windowDays','touch','payoutTerms']:tab==='portal'?['portalMessage']:['dashboardMode','title','salesmanLabel','structureLabel','payoutLabel','mediaLabel'];setDraft(d=>({...d,...Object.fromEntries(keys.map(k=>[k,(defaults as any)[k]]))}));}}>Restore Default</Action><Action primary type="submit" disabled={busy||pref.loading}>{busy?'Saving…':'Save'}</Action></div></form>:tab==='pipeline'?<PipelinePolicy onNotice={m=>{setNotice(m);setError('');}} onError={setError}/>:tab==='accounting'?<TrackerPage resource="settings"/>:tab==='sync'?<TrackerPage resource="integrations"/>:<><h2>Permissions & App Settings</h2><p className="st-help">Your existing access controls, documents settings and data tools remain available.</p><Link className="st-button st-primary" to="/settings">Open App Settings</Link></>}
 </section></div></div>;
}
/** Which provider pipeline/stages count as a won deal, and whether won deals post a receipt for their owner automatically. Ids come from synced opportunities and staged provider events; anything else can be typed. */
function PipelinePolicy({onNotice,onError}:{onNotice:(m:string)=>void;onError:(m:string)=>void}){
 const tracker=useTracker(),saved=tracker.workspace?.pipeline_policy||{},installed=tracker.workspace&&'pipeline_policy' in tracker.workspace;
 const [policy,setPolicy]=useState<any>({pipelineId:saved.pipelineId||'',wonStageIds:Array.isArray(saved.wonStageIds)?saved.wonStageIds:[],treatStatusWonAsWon:saved.treatStatusWonAsWon!==false,auto:saved.auto===true,receipt:saved.receipt==='confirmed'?'confirmed':'pending'}),[extra,setExtra]=useState(''),[busy,setBusy]=useState(false);
 const opportunities=useRemote('opportunities',{limit:'100',sort:'recent',direction:'desc'}),imports=useRemote('imports',{limit:'100',sort:'recent',direction:'desc'});
 // Known pipeline/stage ids: synced opportunity rows plus the staged provider payloads that have not been imported yet.
 const known=useMemo(()=>{const pipelines=new Map<string,Set<string>>();const add=(p:any,s:any)=>{const pid=String(p||''),sid=String(s||'');if(!pid&&!sid)return;if(!pipelines.has(pid))pipelines.set(pid,new Set());if(sid)pipelines.get(pid)!.add(sid);};for(const r of opportunities.data?.rows||[])add(r.pipeline_id,r.stage_id);for(const r of imports.data?.rows||[])if(r.resource==='opportunities')add(r.payload?.pipelineId,r.payload?.stageId);return pipelines;},[opportunities.data,imports.data]);
 const stages=[...new Set([...(policy.pipelineId?[...(known.get(policy.pipelineId)||[])]:[...known.values()].flatMap(s=>[...s])),...policy.wonStageIds])].sort();
 const toggleStage=(id:string,on:boolean)=>setPolicy((p:any)=>({...p,wonStageIds:on?[...new Set([...p.wonStageIds,id])]:p.wonStageIds.filter((s:string)=>s!==id)}));
 const addExtra=()=>{const ids=extra.split(',').map(s=>s.trim()).filter(Boolean);if(ids.length)setPolicy((p:any)=>({...p,wonStageIds:[...new Set([...p.wonStageIds,...ids])]}));setExtra('');};
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);onError('');try{const r=await trackerPost('pipelinePolicy',{...policy,pipelineId:policy.pipelineId||null});setPolicy((p:any)=>({...p,...r.policy,pipelineId:r.policy.pipelineId||''}));tracker.refresh();onNotice(r.policy.auto?'Pipeline policy saved. Won provider deals now post automatically for their owner.':'Pipeline policy saved. Won provider deals post when you approve them in Import review.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}}>
 <h2>Pipeline → commission</h2><p className="st-help">Commission comes from actual pipeline deals. When a synced Kleeger opportunity reaches a won stage, its owner gets a receipt for the deal value (key <code>opportunity:&lt;id&gt;</code>, so provider updates never post twice). Local opportunities entered by hand never create commission.</p>
 {!installed&&<Message error="The reviewed additive database migration must be applied before this policy can be saved."/>}
 <div className="st-form-grid"><Field label="Pipeline (optional)" hint="Leave empty to watch every pipeline."><input list="st-pipeline-ids" value={policy.pipelineId} placeholder="Pipeline id" onChange={e=>setPolicy({...policy,pipelineId:e.target.value.trim()})}/><datalist id="st-pipeline-ids">{[...known.keys()].filter(Boolean).map(id=><option key={id} value={id}/>)}</datalist></Field>
 <Field label="Receipt status for won deals" hint="Pending receipts appear in Payments and post commission when you confirm collection. Confirmed posts commission immediately."><select value={policy.receipt} onChange={e=>setPolicy({...policy,receipt:e.target.value})}><option value="pending">Pending until collection is confirmed</option><option value="confirmed">Confirmed — post commission now</option></select></Field></div>
 <fieldset className="st-disclosure st-policy-toggles"><legend>Won conditions</legend><label className="st-check"><input type="checkbox" checked={policy.treatStatusWonAsWon} onChange={e=>setPolicy({...policy,treatStatusWonAsWon:e.target.checked})}/>Treat provider status <code>won</code> as won</label>
 <p className="st-help">Won stages{policy.pipelineId?` in ${policy.pipelineId}`:''}. {stages.length?'Tick the stages that mean a deal closed.':'No stage ids are known yet — preview an opportunity page under Integrations & Sync, or type stage ids below.'}</p>
 {stages.length>0&&<div className="st-stage-grid">{stages.map(id=><label key={id} className="st-check"><input type="checkbox" checked={policy.wonStageIds.includes(id)} onChange={e=>toggleStage(id,e.target.checked)}/><code>{id}</code></label>)}</div>}
 <div className="st-row-buttons"><input aria-label="Additional won stage ids" placeholder="Stage ids, comma separated" value={extra} onChange={e=>setExtra(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addExtra();}}}/><Action onClick={addExtra} disabled={!extra.trim()}>Add stage ids</Action></div></fieldset>
 <fieldset className="st-disclosure st-policy-toggles"><legend>Automation</legend><label className="st-check"><input type="checkbox" checked={policy.auto} onChange={e=>setPolicy({...policy,auto:e.target.checked})}/>Apply verified provider events automatically</label><p className="st-help">Off: contact and opportunity webhooks wait in Import review, and a won deal posts when you approve it. On: matched events import as they arrive; unmatched contacts, missing owners and commission problems still stop in review with the reason recorded.</p></fieldset>
 <div className="st-dialog-footer"><Action disabled={busy} onClick={()=>setPolicy({pipelineId:'',wonStageIds:[],treatStatusWonAsWon:true,auto:false,receipt:'pending'})}>Restore Default</Action><Action primary type="submit" disabled={busy||!installed}>{busy?'Saving…':'Save'}</Action></div></form>;
}
