import {lazy} from 'react';
import CampaignActivity from '../../components/tracker/CampaignActivity';
import {useEffect,useMemo,useState} from 'react';
import {Upload,Plus,X} from 'lucide-react';
import CampaignSource,{sourceLabel} from '../../components/tracker/CampaignSource';
import CampaignLinks from '../../components/tracker/CampaignLinks';
import {Modal} from '../../components/ui';
import {DecimalInput,RuleEditor,Reference} from '../../components/TrackerForm';
import {useTracker} from '../../components/TrackerGate';
import {trackerGet,trackerPost,trackerCSV} from '../../lib/tracker-client';
import {calculateExact,clientSchedule,compileLayers,decimalToMinor,decompileLayers,displayMinor,layerName,layerPresets,validatePlan,LAYER_TYPES,type ExactPlan,type Layer} from '../../lib/exact-commission';
import {Action,Badge,Empty,ExportIcon,Field,Header,Message,Pager,SearchBox,Steps,Tabs,useRemote,usePreferences} from '../../components/tracker/Experience';
const TrackerPage=lazy(()=>import('../TrackerPage'));
export default function Structures(){
 const [tab,setTab]=useState('structures'),[q,setQ]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[dialog,setDialog]=useState(false),[edit,setEdit]=useState<any>(null),[links,setLinks]=useState<any>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [activity,setActivity]=useState<any>(null);
 const state=useRemote('campaigns',{q,page:String(page),limit:'10',sort:'name'},revision),pref=usePreferences();
 return <div className="st-page"><Header title={pref.values.structureLabel} description="Set your commission rules, assign salesmen and share referral links."><Action onClick={()=>void trackerCSV('campaigns',{q}).catch(e=>setError(e.message))}><ExportIcon/>Export</Action><Action primary onClick={()=>setDialog(true)}><Plus size={16}/>Create Campaign</Action></Header><Tabs tabs={[{id:'structures',label:'Campaigns'},{id:'plans',label:'Commission Plans'},{id:'assignments',label:'Assignments'},{id:'campaigns',label:'Referral Links & Campaigns'},{id:'legacyPlans',label:'Earlier Plans'}]} value={tab} onChange={setTab}/><Message error={error||state.error} notice={notice}/>
 {tab!=='structures'?<TrackerPage key={tab} resource={tab}/>:<section className="st-panel"><div className="st-toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder="Search Sales Commission Structure"/><span className="st-muted">{state.data?.total||0} structures</span></div>{state.loading?<p className="st-loading" role="status">Loading structures…</p>:state.data?.rows.length?<div className="st-table-wrap"><table className="st-table st-campaigns-table"><thead><tr>{['Campaign','Start date','Source','Visits','Captured leads','Test orders','Status','Actions'].map((x,i)=><th key={i} className={x==='Actions'?'st-action-cell':undefined}>{x}</th>)}</tr></thead><tbody>{state.data.rows.map((r:any)=><tr key={r.id}><td><strong>{r.name}</strong><small className="st-block st-muted">{r.description}</small></td><td>{String(r.starts_at||'').slice(0,10)||'Available now'}</td><td>{sourceLabel(r)}</td><td>{r.clicks}</td><td>{r.conversions}</td><td>{r.test_orders||0}</td><td><Badge value={r.status}/></td><td className="st-action-cell"><div className="st-row-buttons"><Action onClick={()=>setLinks(r)}>Affiliate links</Action><Action onClick={()=>setEdit(r)}>Edit</Action>{!['form','survey','calendar','native'].includes(r.tracking_policy?.source?.selection?.kind|| (r.conversion_mode==='native'?'native':''))&&<Action onClick={()=>setActivity(r)}>View orders</Action>}<Action onClick={()=>setTab('campaigns')}>Manage</Action></div></td></tr>)}</tbody></table></div>:<Empty title="Create your first commission structure" description="Choose how to capture leads, set commission rules, then assign your salesmen."><Action primary onClick={()=>setDialog(true)}>Create Campaign</Action></Empty>}<Pager page={page} limit={10} total={state.data?.total||0} onPage={setPage}/></section>}
 {activity&&<Modal open title={`${activity.name} — Orders`} size="xl" onClose={()=>setActivity(null)}><CampaignActivity campaignId={activity.id}/></Modal>}
 {links&&<Modal open title={links.name} size="xl" onClose={()=>setLinks(null)}><CampaignLinks campaignId={links.id} status={links.status} destination={links.destination_url}/></Modal>}
 {(dialog||edit)&&<StructureWizard key={edit?.id||'new'} existing={edit} defaults={pref.values} onClose={()=>{setDialog(false);setEdit(null);}} onSaved={()=>{setNotice(edit?'Campaign updated.':'Campaign created. Copy a salesman’s affiliate link to start tracking.');setDialog(false);setEdit(null);setRevision(r=>r+1);}}/>}</div>;
}
function StructureWizard({onClose,onSaved,defaults:settings,existing}:{onClose:()=>void;onSaved:()=>void;defaults:any;existing?:any}){
 const {workspace}=useTracker(),currency=workspace?.currency||'USD',digits=workspace?.payout_terms?.minorDigits??2;
 // Per-product commission (Wave 3): map specific products to specific plan versions for THIS campaign.
 const productsRemote=useRemote('products',{limit:'100',status:'active'}),plansRemote=useRemote('plans',{limit:'100'});
 const [productMap,setProductMap]=useState<{productId:string;planVersionId:string}[]>([]);
 // Only persist the product→structure map once it has actually loaded, so a failed
 // load can never turn into an empty replace-set that wipes existing mappings.
 const [structLoaded,setStructLoaded]=useState(!existing);
 const defaultRate=()=>{try{return decimalToMinor(String(settings.commissionRate||'10'),2);}catch{return '1000';}};
 const [step,setStep]=useState(0),[b,setB]=useState<any>(()=>existing?{name:existing.name||'',description:existing.description||'',effectiveFrom:new Date().toISOString().slice(0,10),startsAt:String(existing.starts_at||'').slice(0,10),endsAt:String(existing.ends_at||'').slice(0,10),conversionMode:existing.conversion_mode||'external',sourceKind:existing.tracking_policy?.source?.selection?.kind||(existing.conversion_mode==='native'?'native':'external'),source:existing.tracking_policy?.source||null,destinationUrl:existing.destination_url||'',automation:existing.tracking_policy?.automation||'off',config:null,windowDays:Number(existing.tracking_policy?.windowDays)||Number(settings.windowDays),touch:existing.tracking_policy?.touch||settings.touch,participantIds:[],status:existing.status||'active',terms:existing.terms||''}:{name:'',description:'',effectiveFrom:new Date().toISOString().slice(0,10),conversionMode:'external',sourceKind:'funnel',config:compileLayers([{id:'standard',type:'percent',value:defaultRate(),from:1}],{currency,minorDigits:digits,holdDays:Number(settings.holdDays)||0}),windowDays:Number(settings.windowDays),touch:settings.touch,participantIds:[],status:'active',terms:settings.payoutTerms}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<any>(null),[created,setCreated]=useState<any>(null);
 // Simple mode: the plan is always the compilation of `layers` + `hold`; advanced mode edits the compiled rules directly and decompiles back when the shape still fits.
 const [advanced,setAdvanced]=useState(false),[layers,setLayers]=useState<Layer[]>(()=>[{id:'standard',type:'percent',value:defaultRate(),from:1}]),[hold,setHold]=useState(Number(settings.holdDays)||0),[sample,setSample]=useState(()=>decimalToMinor('1000',digits)),[loading,setLoading]=useState(!!existing);
 const applyLayers=(next:Layer[],h=hold)=>{setLayers(next);setHold(h);set('config',compileLayers(next,{currency,minorDigits:digits,holdDays:h}));};
 // Editing prefills the wizard from the saved plan version and the campaign's links; existing link ids are never regenerated by an update.
 useEffect(()=>{if(!existing)return;let live=true;(async()=>{try{
  const [plans,links,struct]=await Promise.all([existing.plan_version_id?trackerGet('plans',{id:existing.plan_version_id}):Promise.resolve(null),trackerGet('links',{campaignId:existing.id,limit:'100'}),trackerGet('campaignStructures',{campaignId:existing.id}).catch(()=>null)]);
  if(!live)return;
  if(struct){setProductMap((struct.map||[]).map((m:any)=>({productId:m.productId,planVersionId:m.planVersionId})));setStructLoaded(true);}
  const version=plans?.rows?.[0],config=version?.config||null;
  setB((v:any)=>({...v,config:config||v.config||compileLayers(layers,{currency,minorDigits:digits,holdDays:hold}),effectiveFrom:version?String(version.effective_from||'').slice(0,10)||v.effectiveFrom:v.effectiveFrom,participantIds:links.rows.filter((r:any)=>r.active).map((r:any)=>r.salesperson_id)}));
  const simple=decompileLayers(config);
  if(simple){setLayers(simple.layers);setHold(simple.holdDays);}else if(config)setAdvanced(true);
 }catch(e){if(live)setError((e as Error).message);}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[existing?.id]);
 const set=(key:string,value:any)=>{setB((v:any)=>({...v,[key]:value}));setReview(null);};
 if(created)return <Modal open title="Structure created" size="xl" onClose={onSaved}><div className="st-dialog"><CampaignLinks campaignId={created.id} status={b.status} destination={b.destinationUrl}/><div className="st-dialog-footer"><Action primary onClick={onSaved}>Done</Action></div></div></Modal>;
 return <Modal open title={existing?'Edit Campaign':'New Campaign'} size="xl" onClose={()=>{if(!busy)onClose();}}><div className="st-dialog"><Steps labels={['Choose Source','Set Commission','Assign Salesmen']} step={step}/><Message error={error}/>{loading&&<p className="st-loading" role="status">Loading campaign details…</p>}<form onSubmit={async e=>{e.preventDefault();setError('');if(step<2){if(!workspace){setError('Complete currency and timezone in Settings before creating a structure.');return;}if(step===0&&b.sourceKind&&!['native','external'].includes(b.sourceKind)&&!b.source){setError('Select a connected asset before continuing.');return;}if(step===1){try{validatePlan(b.config);}catch(e){setError((e as Error).message);return;}setReview({ok:true});}setStep(step+1);return;}setBusy(true);try{if(!b.participantIds.length)throw new Error('Select at least one salesman to create affiliate links.');if(existing){await trackerPost('updateStructure',{...b,id:existing.id});if(structLoaded)await trackerPost('setCampaignStructures',{campaignId:existing.id,map:productMap.filter(m=>m.productId&&m.planVersionId)});onSaved();return;}setCreated(await trackerPost('structure',b));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {step===0&&<><div className="st-form-grid"><Field label="Campaign name *"><input required value={b.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Commission starts on *"><input type="date" required value={b.effectiveFrom} onChange={e=>set('effectiveFrom',e.target.value)}/></Field></div><Field label="Description"><textarea value={b.description} onChange={e=>set('description',e.target.value)}/></Field><CampaignSource value={b} onChange={patch=>{setB((v:any)=>({...v,...patch}));setReview(null);}}/><details className="st-disclosure"><summary>Dates, referral window & terms</summary><div className="st-form-grid"><Field label="Start date"><input type="date" value={b.startsAt||''} onChange={e=>set('startsAt',e.target.value)}/></Field><Field label="End date"><input type="date" value={b.endsAt||''} onChange={e=>set('endsAt',e.target.value)}/></Field><Field label="Cookie life (days)"><input type="number" min="1" max="365" value={b.windowDays} onChange={e=>set('windowDays',Number(e.target.value))}/></Field><Field label="Attribution"><select value={b.touch} onChange={e=>set('touch',e.target.value)}><option value="first">First referral</option><option value="last">Last referral</option></select></Field></div><Field label="Terms"><textarea value={b.terms||''} onChange={e=>set('terms',e.target.value)}/></Field></details></>}
 {step===1&&<>{!advanced&&<LayerBuilder layers={layers} hold={hold} currency={currency} digits={digits} defaultRate={defaultRate()} onChange={applyLayers}/>}<label className="st-field"><span><input type="checkbox" checked={advanced} onChange={e=>{setAdvanced(e.target.checked);if(e.target.checked)return;const simple=decompileLayers(b.config);if(simple)applyLayers(simple.layers,simple.holdDays);else{applyLayers(layers,hold);setError('Those advanced rules cannot be shown as layers, so the builder restored your previous layers. Re-enable advanced rules to keep editing them.');}}}/> Use advanced commission rules {advanced?'(your layers were carried over as rules)':'(beneficiaries, splits, tiers, products, release timing)'}</span></label>{advanced&&<><div className="st-toolbar"><p>Choose a template or build your own commission rules.</p><label className="st-button"><Upload size={15}/>Import rule file<input className="sr-only" type="file" accept=".json,application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>100000)throw new Error('Rule file is too large.');const config=JSON.parse(await file.text()) as ExactPlan;if(config.currency!==currency||config.minorDigits!==digits)throw new Error('Imported rules must use your workspace currency and decimal precision.');validatePlan(config);set('config',config);}catch(e){setError((e as Error).message);}}}/></label></div><RuleEditor currency={currency} digits={digits} value={b.config} onChange={v=>set('config',v)}/></>}<SchedulePreview plan={b.config} sample={sample} onSample={setSample} currency={currency} digits={digits} date={b.effectiveFrom||new Date().toISOString().slice(0,10)}/>{b.config&&b.source?.selection?.checkout?.products?.length>0&&<div className="st-disclosure"><h3>Commission preview for your products</h3>{b.source.selection.checkout.products.map((p:any)=>{if(p.amount==null)return <p key={p.id}>{p.name}: commission uses the verified amount paid at checkout.</p>;try{const amount=decimalToMinor(String(p.amount),digits);const earnings=calculateExact(b.config,{event:'payment',amountMinor:amount,taxMinor:'0',feeMinor:'0',discountMinor:'0',currency:p.currency,productId:p.productId,chargeNumber:1,date:b.effectiveFrom,beneficiaries:{referrer:'preview'}});return <p key={p.id}>{p.name}: {displayMinor(amount,p.currency,digits)} sale → {displayMinor(earnings.reduce((n,e)=>n+BigInt(e.amountMinor),0n).toString(),p.currency,digits)} commission</p>;}catch{return <p key={p.id}>Complete valid commission rules to see the preview.</p>;}})}<p className="st-help">First payment estimate before refunds, fees and any later recurring charges.</p></div>}
 {existing?<details className="st-disclosure"><summary>Different commission for specific products (optional)</summary><p className="st-help">By default every sale in this campaign uses the commission above. Map a product to another commission plan version to pay it differently — everything else keeps the default.</p><ProductCommissionMap map={productMap} onChange={setProductMap} products={productsRemote.data?.rows||[]} plans={plansRemote.data?.rows||[]}/></details>:<p className="st-help">Tip: after you create this campaign, open it again to set a different commission for specific products.</p>}</>}
 {step===2&&<><Reference field={{key:'participantIds',label:'Salesmen',type:'multi',resource:'people'}} value={b.participantIds} onChange={v=>set('participantIds',v)}/><Field label="Launch status"><select value={b.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft — prepare before launch</option><option value="active">Active — enable referral links</option>{existing&&<option value="paused">Paused — referral links temporarily disabled</option>}{existing&&!['draft','active','paused'].includes(b.status)&&<option value={b.status}>{b.status[0].toUpperCase()+b.status.slice(1)}</option>}</select></Field><p className="st-help">Each selected salesman gets their own affiliate link for this campaign. Copy it from their Salesman profile or the campaign. Connected checkouts report verified purchases on your Dashboard. Other sources need submission or payment capture configured before testing.</p>{review&&<div className="st-success"><strong>Ready to {existing?'save':'create'} {b.name}</strong><p>{b.participantIds.length} salesmen · {b.config?.rules.length} rules · Starts {b.effectiveFrom}. Final save checks assignments and {existing?'applies every change together. Existing affiliate links keep working.':'creates everything together.'}</p></div>}</>}
 <div className="st-dialog-footer">{step>0&&<Action disabled={busy} onClick={()=>setStep(step-1)}>Back</Action>}<Action disabled={busy} onClick={onClose}>Cancel</Action><Action primary type="submit" disabled={busy||loading}>{busy?'Checking…':step===0?'Set Up Commission':step===1?'Assign Salesmen':existing?'Save Changes':'Create Campaign'}</Action></div></form></div></Modal>;
}
/** Simple mode of wizard step 2: layers a campaign owner reads top to bottom ("$500 signup bonus + 20% of month 1 + …"). Month N = the customer's Nth confirmed payment. */
function LayerBuilder({layers,hold,currency,digits,defaultRate,onChange}:{layers:Layer[];hold:number;currency:string;digits:number;defaultRate:string;onChange:(layers:Layer[],hold?:number)=>void}){
 const unit=(n:number)=>(BigInt(n)*10n**BigInt(digits)).toString(),presets=layerPresets(digits,defaultRate);
 const patch=(i:number,p:Partial<Layer>)=>onChange(layers.map((l,j)=>j===i?{...l,...p}:l));
 const retype=(i:number,type:Layer['type'])=>patch(i,{type,value:type==='percent'?defaultRate:unit(type==='bonus'?500:100),from:1,to:undefined});
 const sentence=layers.map(l=>layerName(l,currency,digits)).join(' + ');
 return <div className="st-builder"><div className="st-builder-head"><div><h3>Structure builder</h3><p className="st-help">Stack as many layers as you need. Percentages and flat amounts can change over time by month range; a signup bonus is paid once on the customer's first sale.</p></div><div className="st-presets" aria-label="Quick presets">{Object.entries(presets).map(([k,p])=><Action key={k} onClick={()=>onChange(p.layers)}>{p.label}</Action>)}</div></div>
  {layers.length?<ol className="st-layers">{layers.map((l,i)=>{const bad=l.to!==undefined&&l.to<l.from;return <li key={l.id} className="st-layer"><b className="st-layer-index">{i+1}</b>
   <Field label="Type"><select value={l.type} onChange={e=>retype(i,e.target.value as Layer['type'])}>{Object.entries(LAYER_TYPES).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></Field>
   <Field label={l.type==='percent'?'Rate (%)':`Amount (${currency})`}><DecimalInput key={l.type} className="" label={l.type==='percent'?'Rate percent':'Amount'} value={l.value} digits={l.type==='percent'?2:digits} onChange={v=>patch(i,{value:v})}/></Field>
   {l.type==='bonus'?<p className="st-layer-note st-help">Paid once, with the customer's first confirmed payment.</p>:<><Field label="From month"><input type="number" min="1" value={l.from} onChange={e=>patch(i,{from:Math.max(1,Number(e.target.value)||1)})}/></Field><Field label="To month" hint={bad?'Must be at least the from month.':undefined}><input type="number" min={l.from} placeholder="Ongoing" value={l.to??''} onChange={e=>patch(i,{to:e.target.value===''?undefined:Math.max(1,Number(e.target.value)||1)})}/></Field></>}
   <button type="button" className="st-button st-layer-remove" aria-label={`Remove layer ${i+1}`} onClick={()=>onChange(layers.filter((_,j)=>j!==i))}><X size={14}/></button></li>;})}</ol>:<p className="st-alert">Add at least one layer or pick a preset.</p>}
  <div className="st-builder-foot"><Action onClick={()=>onChange([...layers,{id:crypto.randomUUID(),type:'percent',value:defaultRate,from:layers.length?Math.max(...layers.map(l=>l.to??l.from))+1:1}])}><Plus size={15}/>Add layer</Action><label className="st-field st-hold"><span>Hold days before payout</span><input type="number" min="0" max="3650" value={hold} onChange={e=>onChange(layers,Math.max(0,Number(e.target.value)||0))}/></label></div>
  {sentence&&<p className="st-builder-sentence"><strong>Your structure:</strong> {sentence}. Held {hold} days after each payment.</p>}</div>;
}
/** Map products -> commission plan versions for one campaign (setCampaignStructures). Unmapped products fall back to the campaign's default commission. */
function ProductCommissionMap({map,onChange,products,plans}:{map:{productId:string;planVersionId:string}[];onChange:(m:{productId:string;planVersionId:string}[])=>void;products:any[];plans:any[]}){
 const set=(i:number,p:Partial<{productId:string;planVersionId:string}>)=>onChange(map.map((m,j)=>j===i?{...m,...p}:m));
 return <div className="st-product-map">{map.map((m,i)=><div key={i} className="st-product-map-row"><Field label="Product"><select value={m.productId} onChange={e=>set(i,{productId:e.target.value})}><option value="">Choose product…</option>{products.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Pays this commission"><select value={m.planVersionId} onChange={e=>set(i,{planVersionId:e.target.value})}><option value="">Choose plan version…</option>{plans.map((p:any)=><option key={p.id} value={p.id}>{p.name} · v{p.version}</option>)}</select></Field><button type="button" className="st-button st-layer-remove" aria-label={`Remove mapping ${i+1}`} onClick={()=>onChange(map.filter((_,j)=>j!==i))}><X size={14}/></button></div>)}<Action onClick={()=>onChange([...map,{productId:'',planVersionId:''}])}><Plus size={15}/>Add product mapping</Action>{!plans.length&&<p className="st-help">Create commission plan versions first (they appear in the list once published).</p>}</div>;
}
/** Live 12-month schedule for one customer paying the sample amount monthly, computed by the same forecast engine used in reports. */
function SchedulePreview({plan,sample,onSample,currency,digits,date}:{plan:ExactPlan|null;sample:string;onSample:(v:string)=>void;currency:string;digits:number;date:string}){
 const schedule=useMemo(()=>{try{if(!plan)throw new Error('Add a commission layer to see the preview.');return {ok:true as const,...clientSchedule(plan,sample,currency,date,12)};}catch(e){return {ok:false as const,error:(e as Error).message};}},[plan,sample,currency,date]);
 const money=(v:string)=>displayMinor(v,currency,digits);
 return <div className="st-disclosure st-preview"><div className="st-preview-head"><h3>12-month preview for one customer</h3><label className="st-field st-sample"><span>Sample monthly payment ({currency})</span><DecimalInput className="" label="Sample monthly payment" value={sample} digits={digits} onChange={onSample}/></label></div>
  {schedule.ok?<><div className="st-preview-stats"><span><small>Signup bonus (first sale)</small><strong>{money(schedule.bonusMinor)}</strong></span><span><small>Total first-year commission</small><strong>{money(schedule.totalMinor)}</strong></span></div><div className="st-table-wrap"><table className="st-table st-preview-table"><thead><tr><th>Month</th><th>Payment</th><th>Commission this month</th><th>Cumulative</th></tr></thead><tbody>{schedule.rows.map(r=><tr key={r.month}><td>Month {r.month}</td><td>{money(r.paymentMinor)}</td><td>{money(r.commissionMinor)}{r.month===1&&schedule.bonusMinor!=='0'?<small className="st-block st-muted">incl. {money(schedule.bonusMinor)} bonus</small>:null}</td><td>{money(r.cumulativeMinor)}</td></tr>)}</tbody></table></div><p className="st-help">Estimate before refunds, taxes and fees; assumes the customer pays the same amount every month and never churns.</p></>:<p className="st-help">{schedule.error}</p>}</div>;
}
