import {lazy} from 'react';
import CampaignActivity from '../../components/tracker/CampaignActivity';
import {useState} from 'react';
import {Upload,Plus} from 'lucide-react';
import CampaignSource,{sourceLabel} from '../../components/tracker/CampaignSource';
import CampaignLinks from '../../components/tracker/CampaignLinks';
import {Modal} from '../../components/ui';
import {RuleEditor,Reference} from '../../components/TrackerForm';
import {useTracker} from '../../components/TrackerGate';
import {trackerPost,trackerCSV} from '../../lib/tracker-client';
import {calculateExact,decimalToMinor,displayMinor,validatePlan,type ExactPlan} from '../../lib/exact-commission';
import {Action,Badge,Empty,ExportIcon,Field,Header,Message,Pager,SearchBox,Steps,Tabs,useRemote,usePreferences} from '../../components/tracker/Experience';
const TrackerPage=lazy(()=>import('../TrackerPage'));
export default function Structures(){
 const [tab,setTab]=useState('structures'),[q,setQ]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[dialog,setDialog]=useState(false),[links,setLinks]=useState<any>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [activity,setActivity]=useState<any>(null);
 const state=useRemote('campaigns',{q,page:String(page),limit:'10',sort:'name'},revision),pref=usePreferences();
 return <div className="st-page"><Header title={pref.values.structureLabel} description="Set your commission rules, assign salesmen and share referral links."><Action onClick={()=>void trackerCSV('campaigns',{q}).catch(e=>setError(e.message))}><ExportIcon/>Export</Action><Action primary onClick={()=>setDialog(true)}><Plus size={16}/>Create Campaign</Action></Header><Tabs tabs={[{id:'structures',label:'Campaigns'},{id:'plans',label:'Commission Plans'},{id:'assignments',label:'Assignments'},{id:'campaigns',label:'Referral Links & Campaigns'},{id:'legacyPlans',label:'Earlier Plans'}]} value={tab} onChange={setTab}/><Message error={error||state.error} notice={notice}/>
 {tab!=='structures'?<TrackerPage key={tab} resource={tab}/>:<section className="st-panel"><div className="st-toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder="Search Sales Commission Structure"/><span className="st-muted">{state.data?.total||0} structures</span></div>{state.loading?<p className="st-loading" role="status">Loading structures…</p>:state.data?.rows.length?<div className="st-table-wrap"><table className="st-table st-campaigns-table"><thead><tr>{['Campaign','Start date','Source','Visits','Live customers','Test orders','Status','Actions'].map((x,i)=><th key={i} className={x==='Actions'?'st-action-cell':undefined}>{x}</th>)}</tr></thead><tbody>{state.data.rows.map((r:any)=><tr key={r.id}><td><strong>{r.name}</strong><small className="st-block st-muted">{r.description}</small></td><td>{String(r.starts_at||'').slice(0,10)||'Available now'}</td><td>{sourceLabel(r)}</td><td>{r.clicks}</td><td>{r.conversions}</td><td>{r.test_orders||0}</td><td><Badge value={r.status}/></td><td className="st-action-cell"><div className="st-row-buttons"><Action onClick={()=>setLinks(r)}>Affiliate links</Action><Action onClick={()=>setActivity(r)}>View orders</Action><Action onClick={()=>setTab('campaigns')}>Manage</Action></div></td></tr>)}</tbody></table></div>:<Empty title="Create your first commission structure" description="Choose how to capture leads, set commission rules, then assign your salesmen."><Action primary onClick={()=>setDialog(true)}>Create Campaign</Action></Empty>}<Pager page={page} limit={10} total={state.data?.total||0} onPage={setPage}/></section>}
 {activity&&<Modal open title={`${activity.name} — Orders`} size="xl" onClose={()=>setActivity(null)}><CampaignActivity campaignId={activity.id}/></Modal>}
 {links&&<Modal open title={links.name} size="xl" onClose={()=>setLinks(null)}><CampaignLinks campaignId={links.id} status={links.status} destination={links.destination_url}/></Modal>}
 {dialog&&<StructureWizard defaults={pref.values} onClose={()=>setDialog(false)} onSaved={()=>{setDialog(false);setNotice('Campaign created. Copy a salesman’s affiliate link to start tracking.');setRevision(r=>r+1);}}/>}</div>;
}
function StructureWizard({onClose,onSaved,defaults:settings}:{onClose:()=>void;onSaved:()=>void;defaults:any}){
 const {workspace}=useTracker(),currency=workspace?.currency||'USD',digits=workspace?.payout_terms?.minorDigits??2;
 const [step,setStep]=useState(0),[b,setB]=useState<any>({name:'',description:'',effectiveFrom:new Date().toISOString().slice(0,10),conversionMode:'external',sourceKind:'funnel',config:{currency,minorDigits:digits,rules:[{id:'standard',name:'Sales commission',event:'payment',kind:'percent',value:decimalToMinor(settings.commissionRate,2),beneficiary:'referrer',base:'gross',chargeFrom:1,holdDays:Number(settings.holdDays),group:'commission',stacking:'exclusive',priority:1}]},windowDays:Number(settings.windowDays),touch:settings.touch,participantIds:[],status:'active',terms:settings.payoutTerms}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<any>(null),[created,setCreated]=useState<any>(null);
 const [advanced,setAdvanced]=useState(false),[rate,setRate]=useState(settings.commissionRate);
 const set=(key:string,value:any)=>{setB((v:any)=>({...v,[key]:value}));setReview(null);};
 if(created)return <Modal open title="Structure created" size="xl" onClose={onSaved}><div className="st-dialog"><CampaignLinks campaignId={created.id} status={b.status} destination={b.destinationUrl}/><div className="st-dialog-footer"><Action primary onClick={onSaved}>Done</Action></div></div></Modal>;
 return <Modal open title="New Campaign" size="xl" onClose={()=>{if(!busy)onClose();}}><div className="st-dialog"><Steps labels={['Choose Source','Set Commission','Assign Salesmen']} step={step}/><Message error={error}/><form onSubmit={async e=>{e.preventDefault();setError('');if(step<2){if(!workspace){setError('Complete currency and timezone in Settings before creating a structure.');return;}if(step===0&&b.sourceKind&&!['native','external'].includes(b.sourceKind)&&!b.source){setError('Select a connected asset before continuing.');return;}if(step===1){try{validatePlan(b.config);}catch(e){setError((e as Error).message);return;}}setStep(step+1);return;}setBusy(true);try{if(!b.participantIds.length)throw new Error('Select at least one salesman to create affiliate links.');setCreated(await trackerPost('structure',b));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {step===0&&<><div className="st-form-grid"><Field label="Campaign name *"><input required value={b.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Commission starts on *"><input type="date" required value={b.effectiveFrom} onChange={e=>set('effectiveFrom',e.target.value)}/></Field></div><Field label="Description"><textarea value={b.description} onChange={e=>set('description',e.target.value)}/></Field><CampaignSource value={b} onChange={patch=>{setB((v:any)=>({...v,...patch}));setReview(null);}}/><details className="st-disclosure"><summary>Dates, referral window & terms</summary><div className="st-form-grid"><Field label="Start date"><input type="date" value={b.startsAt||''} onChange={e=>set('startsAt',e.target.value)}/></Field><Field label="End date"><input type="date" value={b.endsAt||''} onChange={e=>set('endsAt',e.target.value)}/></Field><Field label="Cookie life (days)"><input type="number" min="1" max="365" value={b.windowDays} onChange={e=>set('windowDays',Number(e.target.value))}/></Field><Field label="Attribution"><select value={b.touch} onChange={e=>set('touch',e.target.value)}><option value="first">First referral</option><option value="last">Last referral</option></select></Field></div><Field label="Terms"><textarea value={b.terms||''} onChange={e=>set('terms',e.target.value)}/></Field></details></>}
 {step===1&&<><Field label="Commission rate (%)"><input type="number" min="0" max="100" step="0.01" disabled={advanced} value={rate} onChange={e=>{setRate(e.target.value);try{const value=decimalToMinor(e.target.value,2);set('config',{currency,minorDigits:digits,rules:[{id:'standard',name:'Sales commission',event:'payment',kind:'percent',value,beneficiary:'referrer',base:'gross',chargeFrom:1,holdDays:Number(settings.holdDays),group:'commission',stacking:'exclusive',priority:1}]});}catch{set('config',null);}}}/></Field><p className="st-help">Every assigned salesman earns this percentage when a customer pays through their link. These commissions are held for {settings.holdDays} days. Change campaign defaults in Settings or use advanced rules below.</p><label className="st-field"><span><input type="checkbox" checked={advanced} onChange={e=>{setAdvanced(e.target.checked);if(!e.target.checked){set('config',{currency,minorDigits:digits,rules:[{id:'standard',name:'Sales commission',event:'payment',kind:'percent',value:decimalToMinor(rate||'10',2),beneficiary:'referrer',base:'gross',chargeFrom:1,holdDays:Number(settings.holdDays),group:'commission',stacking:'exclusive',priority:1}]});}}}/> Use advanced commission rules</span></label>{advanced&&<><div className="st-toolbar"><p>Choose a template or build your own commission rules.</p><label className="st-button"><Upload size={15}/>Import rule file<input className="sr-only" type="file" accept=".json,application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>100000)throw new Error('Rule file is too large.');const config=JSON.parse(await file.text()) as ExactPlan;if(config.currency!==currency||config.minorDigits!==digits)throw new Error('Imported rules must use your workspace currency and decimal precision.');validatePlan(config);set('config',config);}catch(e){setError((e as Error).message);}}}/></label></div><RuleEditor currency={currency} digits={digits} value={b.config} onChange={v=>set('config',v)}/></>}{b.config&&b.source?.selection?.checkout?.products?.length>0&&<div className="st-disclosure"><h3>Commission preview for your products</h3>{b.source.selection.checkout.products.map((p:any)=>{try{const amount=decimalToMinor(String(p.amount),digits);const earnings=calculateExact(b.config,{event:'payment',amountMinor:amount,taxMinor:'0',feeMinor:'0',discountMinor:'0',currency:p.currency,productId:p.productId,chargeNumber:1,date:b.effectiveFrom,beneficiaries:{referrer:'preview'}});return <p key={p.id}>{p.name}: {displayMinor(amount,p.currency,digits)} sale → {displayMinor(earnings.reduce((n,e)=>n+BigInt(e.amountMinor),0n).toString(),p.currency,digits)} commission</p>;}catch{return <p key={p.id}>Complete valid commission rules to see the preview.</p>;}})}<p className="st-help">First payment estimate before refunds, fees and any later recurring charges.</p></div>}</>}
 {step===2&&<><Reference field={{key:'participantIds',label:'Salesmen',type:'multi',resource:'people'}} value={b.participantIds} onChange={v=>set('participantIds',v)}/><Field label="Launch status"><select value={b.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft — prepare before launch</option><option value="active">Active — enable referral links</option></select></Field><p className="st-help">Each selected salesman gets their own affiliate link for this campaign. Copy it from their Salesman profile or the campaign. Connected checkouts report verified purchases on your Dashboard. Other sources need submission or payment capture configured before testing.</p>{review&&<div className="st-success"><strong>Ready to create {b.name}</strong><p>{b.participantIds.length} salesmen · {b.config?.rules.length} rules · Starts {b.effectiveFrom}. Final save checks assignments and creates everything together.</p></div>}</>}
 <div className="st-dialog-footer">{step>0&&<Action disabled={busy} onClick={()=>setStep(step-1)}>Back</Action>}<Action disabled={busy} onClick={onClose}>Cancel</Action><Action primary type="submit" disabled={busy}>{busy?'Checking…':step===0?'Set Up Commission':step===1?'Assign Salesmen':'Create Campaign'}</Action></div></form></div></Modal>;
}
