import {useState} from 'react';
import {FileText,Globe,Upload,Plus} from 'lucide-react';
import {Modal} from '../../components/ui';
import {RuleEditor,Reference} from '../../components/TrackerForm';
import {useTracker} from '../../components/TrackerGate';
import {trackerPost,trackerCSV} from '../../lib/tracker-client';
import {validatePlan,type ExactPlan} from '../../lib/exact-commission';
import {Action,Badge,Empty,ExportIcon,Field,Header,Message,Pager,SearchBox,Steps,Tabs,useRemote,usePreferences} from '../../components/tracker/Experience';
import TrackerPage from '../TrackerPage';
export default function Structures(){
 const [tab,setTab]=useState('structures'),[q,setQ]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[dialog,setDialog]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const state=useRemote('campaigns',{q,page:String(page),limit:'10',sort:'name'},revision),pref=usePreferences();
 return <div className="st-page"><Header title={pref.values.structureLabel} description="Set your commission rules, assign salesmen and share referral links."><Action onClick={()=>void trackerCSV('campaigns',{q}).catch(e=>setError(e.message))}><ExportIcon/>Export</Action><Action primary onClick={()=>setDialog(true)}><Plus size={16}/>Add Structure</Action></Header><Tabs tabs={[{id:'structures',label:'All Structures'},{id:'plans',label:'Commission Plans'},{id:'assignments',label:'Assignments'},{id:'campaigns',label:'Referral Links & Campaigns'},{id:'legacyPlans',label:'Earlier Plans'}]} value={tab} onChange={setTab}/><Message error={error||state.error} notice={notice}/>
 {tab!=='structures'?<TrackerPage key={tab} resource={tab}/>:<section className="st-panel"><div className="st-toolbar"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1);}} placeholder="Search Sales Commission Structure"/><span className="st-muted">{state.data?.total||0} structures</span></div>{state.loading?<p className="st-loading" role="status">Loading structures…</p>:state.data?.rows.length?<div className="st-table-wrap"><table className="st-table"><thead><tr>{['Structure name','Start date','Source','Clicks','Conversions','Status',''].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{state.data.rows.map((r:any)=><tr key={r.id}><td><strong>{r.name}</strong><small className="st-block st-muted">{r.description}</small></td><td>{String(r.starts_at||'').slice(0,10)||'No start date'}</td><td>{r.conversion_mode==='native'?'Hosted referral form':'External website'}</td><td>{r.clicks}</td><td>{r.conversions}</td><td><Badge value={r.status}/></td><td><Action onClick={()=>setTab('campaigns')}>Manage</Action></td></tr>)}</tbody></table></div>:<Empty title="Create your first commission structure" description="Choose how to capture leads, set commission rules, then assign your salesmen."><Action primary onClick={()=>setDialog(true)}>Add Structure</Action></Empty>}<Pager page={page} limit={10} total={state.data?.total||0} onPage={setPage}/></section>}
 {dialog&&<StructureWizard defaults={pref.values} onClose={()=>setDialog(false)} onSaved={()=>{setDialog(false);setNotice('Structure and dated assignments created.');setRevision(r=>r+1);}}/>}</div>;
}
function StructureWizard({onClose,onSaved,defaults:settings}:{onClose:()=>void;onSaved:()=>void;defaults:any}){
 const {workspace}=useTracker(),currency=workspace?.currency||'USD',digits=workspace?.payout_terms?.minorDigits??2;
 const [step,setStep]=useState(0),[b,setB]=useState<any>({name:'',description:'',effectiveFrom:new Date().toISOString().slice(0,10),conversionMode:'native',windowDays:Number(settings.windowDays),touch:settings.touch,participantIds:[],status:'draft',terms:settings.payoutTerms}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<any>(null);
 const set=(key:string,value:any)=>{setB((v:any)=>({...v,[key]:value}));setReview(null);};
 return <Modal open title="New Sales Commission Structure" size="xl" onClose={()=>{if(!busy)onClose();}}><div className="st-dialog"><Steps labels={['Structure Details','Set Commission','Assign Salesman']} step={step}/><Message error={error}/><form onSubmit={async e=>{e.preventDefault();setError('');if(step<2){if(!workspace){setError('Complete currency and timezone in Settings before creating a structure.');return;}if(step===1){try{validatePlan(b.config);}catch(e){setError((e as Error).message);return;}}setStep(step+1);return;}setBusy(true);try{if(!review){setReview(await trackerPost('structure',{...b,preview:true}));}else{await trackerPost('structure',b);onSaved();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {step===0&&<><div className="st-form-grid"><Field label="Structure name *"><input required value={b.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Commission starts on *"><input type="date" required value={b.effectiveFrom} onChange={e=>set('effectiveFrom',e.target.value)}/></Field></div><Field label="Description"><textarea value={b.description} onChange={e=>set('description',e.target.value)}/></Field><p className="st-help">Choose where this structure captures referrals.</p><div className="st-choice-grid">{[{id:'native',title:'Hosted referral form',text:'Capture leads in your Sales Tracker',icon:<FileText size={23}/>},{id:'external',title:'External website',text:'Track referral clicks to your website',icon:<Globe size={23}/>}].map(c=><button type="button" key={c.id} className={`st-choice ${b.conversionMode===c.id?'is-selected':''}`} onClick={()=>set('conversionMode',c.id)}>{c.icon}<strong>{c.title}</strong><small>{c.text}</small></button>)}</div>{b.conversionMode==='external'&&<Field label="Website URL *" hint="Clicks are tracked. Conversions and receipts from external websites require a verified import; this does not install a Stripe integration."><input type="url" required placeholder="https://your-website.com" value={b.destinationUrl||''} onChange={e=>set('destinationUrl',e.target.value)}/></Field>}<details className="st-disclosure"><summary>Dates, referral window & terms</summary><div className="st-form-grid"><Field label="Start date"><input type="date" value={b.startsAt||''} onChange={e=>set('startsAt',e.target.value)}/></Field><Field label="End date"><input type="date" value={b.endsAt||''} onChange={e=>set('endsAt',e.target.value)}/></Field><Field label="Cookie life (days)"><input type="number" min="1" max="365" value={b.windowDays} onChange={e=>set('windowDays',Number(e.target.value))}/></Field><Field label="Attribution"><select value={b.touch} onChange={e=>set('touch',e.target.value)}><option value="first">First referral</option><option value="last">Last referral</option></select></Field></div><Field label="Terms"><textarea value={b.terms||''} onChange={e=>set('terms',e.target.value)}/></Field></details></>}
 {step===1&&<><div className="st-toolbar"><p>Choose a template or build your own commission rules.</p><label className="st-button"><Upload size={15}/>Import rule file<input className="sr-only" type="file" accept=".json,application/json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>100000)throw new Error('Rule file is too large.');const config=JSON.parse(await file.text()) as ExactPlan;if(config.currency!==currency||config.minorDigits!==digits)throw new Error('Imported rules must use your workspace currency and decimal precision.');validatePlan(config);set('config',config);}catch(e){setError((e as Error).message);}}}/></label></div><RuleEditor currency={currency} digits={digits} value={b.config} onChange={v=>set('config',v)}/></>}
 {step===2&&<><Reference field={{key:'participantIds',label:'Salesmen',type:'multi',resource:'people'}} value={b.participantIds} onChange={v=>set('participantIds',v)}/><Field label="Launch status"><select value={b.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft — prepare before launch</option><option value="active">Active — enable referral links</option></select></Field><p className="st-help">Each selected salesman gets a referral link and a dated commission assignment. Existing earnings stay unchanged. Conflicting assignments must be ended before this structure can be saved.</p>{review&&<div className="st-success"><strong>Ready to create {b.name}</strong><p>{b.participantIds.length} salesmen · {b.config?.rules.length} rules · Starts {b.effectiveFrom}. Final save checks assignments and creates everything together.</p></div>}</>}
 <div className="st-dialog-footer">{step>0&&<Action disabled={busy} onClick={()=>setStep(step-1)}>Back</Action>}<Action disabled={busy} onClick={onClose}>Cancel</Action><Action primary type="submit" disabled={busy}>{busy?'Checking…':step===0?'Set Up Commission':step===1?'Assign Salesman':review?'Create Structure':'Review Structure'}</Action></div></form></div></Modal>;
}
