import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Bell,CheckCheck,MessageSquare,ShieldCheck,Clock,Wallet,Activity} from 'lucide-react';
import {Button,Input,Select} from '../components/ui';
import {proposalRequest} from '../lib/proposal-workspace-client';
const icons:Record<string,typeof Bell>={approval:ShieldCheck,question:MessageSquare,followup:Clock,payout:Wallet,proposal:Activity};
export default function Notifications(){
  const [items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
  const load=useCallback(async()=>{try{const data=await proposalRequest({op:'notifications'},true);setItems(data.items);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[load]);
  async function mark(ids:string[]){setBusy(true);try{await proposalRequest({op:'notification_read',ids});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const visible=items.filter(i=>(filter==='all'||filter==='unread'&&!i.read||filter==='action'&&i.actionRequired||i.category===filter)&&`${i.title} ${i.detail} ${i.documentTitle}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="st-page notification-page"><header className="notification-header"><div><span className="notification-eyebrow">YOUR WORKSPACE</span><h1><Bell size={25}/>Notifications</h1><p>Client questions, internal reviews, follow-ups and payout updates in one place.</p></div><div className="ps-actions"><Button variant="secondary" onClick={()=>void load()}>Refresh</Button><Button disabled={busy||!visible.some(i=>!i.read)} onClick={()=>void mark(visible.filter(i=>!i.read).map(i=>i.id))}><CheckCheck size={16}/>Mark visible as read</Button></div></header>
    <div className="notification-stats"><div><strong>{items.filter(i=>!i.read).length}</strong><span>Unread updates</span></div><div><strong>{items.filter(i=>i.actionRequired).length}</strong><span>Need action</span></div><div><strong>{items.filter(i=>i.category==='question'&&!i.read).length}</strong><span>Client questions</span></div></div>
    <div className="notification-toolbar"><Input aria-label="Search notifications" placeholder="Search proposal or notification…" value={search} onChange={e=>setSearch(e.target.value)}/><Select aria-label="Filter notifications" value={filter} onChange={e=>setFilter(e.target.value)}>{[['all','All notifications'],['unread','Unread'],['action','Needs action'],['approval','Internal approvals'],['question','Client questions'],['proposal','Proposal activity'],['followup','Follow-ups'],['payout','Payouts']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></div>
    {error&&<p role="alert" className="proposal-error">{error}</p>}{loading?<p role="status">Loading notifications…</p>:<section className="notification-list" aria-label="Notifications">{visible.length?visible.map(i=>{const Icon=icons[i.category]||Bell;return <article className={`notification-item ${i.read?'':'is-unread'}`} key={i.id}><span className={`notification-icon ${i.category}`}><Icon size={20}/></span><div className="notification-content"><div className="notification-title"><h2>{i.title}</h2>{!i.read&&<span className="notification-pill">New</span>}{i.actionRequired&&<span className="notification-pill action">Needs action</span>}</div>{i.documentTitle&&<strong>{i.documentTitle}</strong>}<p>{i.detail}</p><small>{i.at&&Number.isFinite(Date.parse(i.at))?new Date(i.at).toLocaleString():'Recent update'}</small></div><div className="notification-actions"><Link to={i.href} onClick={()=>{void mark([i.id]);}}>{i.category==='payout'?'View payout':'Open proposal'} →</Link>{!i.read&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void mark([i.id])}>Mark read</Button>}</div></article>;}):<div className="notification-empty"><Bell size={30}/><h2>You’re all caught up</h2><p>No notifications match this view.</p></div>}</section>}
    <p className="proposal-caption">Updates refresh every 15 seconds. Reading a notification does not approve an offer or complete a payment. Follow-up dates use UTC.</p>
  </div>;
}
