import { useMemo, useState } from "react";
import { Plus, Trash2, Receipt, Search } from "lucide-react";
import { useApp } from "../store/AppContext";
import type { Payment, PaymentType } from "../types";
import {
  PageHeader,
  Button,
  Card,
  EmptyState,
  Badge,
  Field,
  Input,
  Textarea,
  Select,
  NumberField,
  Table,
  THead,
  TBody,
  TR,
  TH,
  TD,
} from "../components/ui";
import { Modal, ConfirmModal } from "../components/ui/Modal";
import { uid, todayISO, formatCurrency, formatDate } from "../lib/format";
import { createPayment, deletePayment } from "../lib/resource-client";

const TYPE_LABEL: Record<PaymentType, string> = {
  setup_fee: "Setup fee",
  monthly_subscription: "Monthly subscription",
  refund: "Refund",
  adjustment: "Adjustment",
};

const TYPE_TONE: Record<PaymentType, "blue" | "green" | "rose" | "amber"> = {
  setup_fee: "blue",
  monthly_subscription: "green",
  refund: "rose",
  adjustment: "amber",
};

function emptyPayment(): Payment {
  return {
    id: uid("pay"),
    clientId: "",
    date: todayISO(),
    type: "monthly_subscription",
    amount: 0,
    paymentNumber: 1,
    notes: "",
    createdAt: todayISO(),
  };
}

export default function Payments() {
  const { data, dispatch, reload } = useApp();
  const [editing, setEditing] = useState<Payment | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const [search, setSearch] = useState("");

  const clientName = (clientId: string) =>
    data.clients.find((c) => c.id === clientId)?.companyName ?? "—";

  // commissions generated by each payment
  const commByPayment = useMemo(() => {
    const m = new Map<string, { count: number; total: number }>();
    for (const e of data.commissions) {
      if (!e.paymentId) continue;
      const cur = m.get(e.paymentId) ?? { count: 0, total: 0 };
      cur.count += 1;
      cur.total += e.commissionAmount;
      m.set(e.paymentId, cur);
    }
    return m;
  }, [data.commissions]);

  const rows = useMemo(() => {
    const q = search.toLowerCase();
    return [...data.payments]
      .sort((a, b) => (a.date < b.date ? 1 : -1))
      .filter((p) => (!q ? true : clientName(p.clientId).toLowerCase().includes(q)));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data.payments, data.clients, search]);

  function openNew() {
    const first = data.clients[0];
    const p = emptyPayment();
    if (first) {
      p.clientId = first.id;
      p.amount = first.monthlySubscription;
    }
    setEditing(p);
  }

  // When the client or type changes, prefill a sensible amount + next payment number.
  function applyClientType(next: Payment): Payment {
    const client = data.clients.find((c) => c.id === next.clientId);
    const copy = { ...next };
    if (next.type === "monthly_subscription") {
      const priorMax = data.payments
        .filter((p) => p.clientId === next.clientId && p.type === "monthly_subscription")
        .reduce((mx, p) => Math.max(mx, p.paymentNumber ?? 0), 0);
      copy.paymentNumber = priorMax + 1;
      if (client && !copy.amount) copy.amount = client.monthlySubscription;
    } else {
      copy.paymentNumber = null;
      if (next.type === "setup_fee" && client && !copy.amount) copy.amount = client.setupFee;
    }
    return copy;
  }

  async function save() {
    if (!editing || !editing.clientId) return;
    const payment = editing;
    try {
      // Real DB API: persist + server-side ledger recompute, then reload
      // authoritative state. Falls back to the local store off the API.
      await createPayment({
        clientId: payment.clientId,
        date: payment.date,
        type: payment.type,
        amount: payment.amount,
        paymentNumber: payment.paymentNumber,
        notes: payment.notes,
      });
      await reload();
    } catch {
      dispatch({ type: "PAYMENT_ADD", payment });
    }
    setEditing(null);
  }

  async function confirmDelete() {
    if (!deleteId) return;
    const id = deleteId;
    try {
      await deletePayment(id);
      await reload();
      setDeleteId(null);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "";
      if (msg === "has_locked_commissions") {
        // A submitted/approved/paid commission depends on this payment — refuse
        // and tell the user instead of corrupting payout history.
        setDeleteId(null);
        setDeleteError(
          "This payment can't be deleted: it has commissions that are already submitted, approved, or paid. Cancel or reject the related payout first.",
        );
        return;
      }
      // Other failure (e.g. local-dev with no API): fall back to the local store.
      dispatch({ type: "PAYMENT_DELETE", id });
      setDeleteId(null);
    }
  }

  return (
    <div>
      <PageHeader
        title="Payments"
        subtitle="Record what clients paid — commissions are calculated automatically by the plan rules"
        actions={
          <Button onClick={openNew} disabled={data.clients.length === 0}>
            <Plus className="h-4 w-4" /> Add payment
          </Button>
        }
      />

      {data.clients.length === 0 && (
        <p className="mb-4 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300">
          Add a client first — payments are always tied to a client.
        </p>
      )}

      <Card padded={false} className="overflow-hidden">
        <div className="flex items-center gap-2 border-b border-slate-100 p-3 dark:border-slate-800">
          <div className="relative flex-1">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by client…"
              className="pl-9"
            />
          </div>
        </div>

        {rows.length === 0 ? (
          <div className="p-6">
            <EmptyState
              icon={<Receipt className="h-6 w-6" />}
              title={data.payments.length === 0 ? "No payments yet" : "No matching payments"}
              description={
                data.payments.length === 0
                  ? "Record a setup fee or monthly subscription to see commissions generated instantly."
                  : "Try a different search."
              }
            />
          </div>
        ) : (
          <Table>
            <THead>
              <TR>
                <TH>Date</TH>
                <TH>Client</TH>
                <TH>Type</TH>
                <TH className="text-right">Amount</TH>
                <TH>Commissions</TH>
                <TH className="text-right">Actions</TH>
              </TR>
            </THead>
            <TBody>
              {rows.map((p) => {
                const comm = commByPayment.get(p.id);
                return (
                  <TR key={p.id}>
                    <TD className="whitespace-nowrap text-slate-500">{formatDate(p.date)}</TD>
                    <TD className="font-medium text-slate-900 dark:text-white">
                      {clientName(p.clientId)}
                    </TD>
                    <TD>
                      <Badge tone={TYPE_TONE[p.type]}>{TYPE_LABEL[p.type]}</Badge>
                      {p.type === "monthly_subscription" && p.paymentNumber != null && (
                        <span className="ml-2 text-xs text-slate-400">#{p.paymentNumber}</span>
                      )}
                    </TD>
                    <TD
                      className={
                        "text-right tabular-nums " +
                        (p.type === "refund" ? "text-rose-500" : "")
                      }
                    >
                      {p.type === "refund" ? "−" : ""}
                      {formatCurrency(p.amount)}
                    </TD>
                    <TD>
                      {comm ? (
                        <span className="text-slate-600 dark:text-slate-300">
                          {comm.count} · {formatCurrency(comm.total)}
                        </span>
                      ) : (
                        <span className="text-xs text-slate-400">none</span>
                      )}
                    </TD>
                    <TD className="text-right">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => setDeleteId(p.id)}
                        aria-label="Delete"
                        className="text-rose-500"
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </TD>
                  </TR>
                );
              })}
            </TBody>
          </Table>
        )}
      </Card>

      <Modal
        open={!!editing}
        onClose={() => setEditing(null)}
        title="Add payment"
        footer={
          <>
            <Button variant="secondary" onClick={() => setEditing(null)}>
              Cancel
            </Button>
            <Button onClick={save} disabled={!editing?.clientId}>
              Add payment
            </Button>
          </>
        }
      >
        {editing && (
          <div className="space-y-4">
            <Field label="Client" required>
              <Select
                value={editing.clientId}
                onChange={(e) =>
                  setEditing(applyClientType({ ...editing, clientId: e.target.value, amount: 0 }))
                }
              >
                <option value="">Select a client…</option>
                {data.clients.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.companyName}
                  </option>
                ))}
              </Select>
            </Field>

            <div className="grid grid-cols-2 gap-3">
              <Field label="Type">
                <Select
                  value={editing.type}
                  onChange={(e) =>
                    setEditing(
                      applyClientType({
                        ...editing,
                        type: e.target.value as PaymentType,
                        amount: 0,
                      }),
                    )
                  }
                >
                  {(Object.keys(TYPE_LABEL) as PaymentType[]).map((t) => (
                    <option key={t} value={t}>
                      {TYPE_LABEL[t]}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field label="Date">
                <Input
                  type="date"
                  value={editing.date}
                  onChange={(e) => setEditing({ ...editing, date: e.target.value })}
                />
              </Field>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <Field label="Amount">
                <NumberField
                  value={editing.amount}
                  onChange={(v) => setEditing({ ...editing, amount: v })}
                  prefix="$"
                  min={0}
                />
              </Field>
              {editing.type === "monthly_subscription" && (
                <Field label="Payment number" hint="Which subscription month this is.">
                  <NumberField
                    value={editing.paymentNumber ?? 1}
                    onChange={(v) => setEditing({ ...editing, paymentNumber: Math.max(1, Math.round(v)) })}
                    min={1}
                  />
                </Field>
              )}
            </div>

            <Field label="Notes">
              <Textarea
                value={editing.notes}
                onChange={(e) => setEditing({ ...editing, notes: e.target.value })}
              />
            </Field>

            <p className="text-xs text-slate-400">
              Setup-fee payments trigger setup + signup-bonus commissions. Monthly payments trigger
              the residual rule that matches the payment number. Refunds and adjustments don't
              generate commissions.
            </p>
          </div>
        )}
      </Modal>

      <ConfirmModal
        open={!!deleteId}
        onClose={() => setDeleteId(null)}
        onConfirm={confirmDelete}
        title="Delete payment?"
        message="The commissions generated by this payment will be removed and totals recalculated."
      />

      <ConfirmModal
        open={!!deleteError}
        onClose={() => setDeleteError(null)}
        onConfirm={() => setDeleteError(null)}
        title="Can't delete this payment"
        message={deleteError ?? ""}
        confirmLabel="OK"
        danger={false}
      />
    </div>
  );
}
