import {useEffect,useRef,useState} from 'react';
export default function ReferralJoin(){
  const [link,setLink]=useState<any>(null),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);const started=useRef(false);
  useEffect(()=>{if(started.current)return;started.current=true;const code=new URLSearchParams(location.search).get('code')||'';fetch(`/api/referral?code=${encodeURIComponent(code)}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.message||'This link is unavailable.');setLink(b);}).catch(e=>setError(e.message));},[]);
  return <main className="mx-auto max-w-lg space-y-5 px-5 py-16"><h1 className="text-3xl font-semibold">{link?.name||'Referral enquiry'}</h1>{error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{!link&&!error&&<p role="status">Loading referral…</p>}{done?<p role="status" className="rounded-xl bg-emerald-50 p-6 text-emerald-900">Thank you. Your enquiry has been received.</p>:link?.mode==='external'?<><p>This campaign uses an external enquiry page. Conversion capture on that page has not been verified.</p><a href={link.destination} rel="noreferrer" className="inline-block rounded-lg bg-slate-900 px-5 py-3 text-white">Continue to campaign page</a></>:link&&<form className="space-y-4" onSubmit={async e=>{e.preventDefault();const fields=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/referral',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clickId:link.clickId,name:fields.get('name'),email:fields.get('email'),phone:fields.get('phone'),consent:fields.get('consent')==='on'})});const b=await r.json();if(!r.ok)throw new Error(b.message||'Your enquiry could not be saved.');setDone(true);}catch(e){setError(e instanceof Error?e.message:'Your enquiry could not be saved.');}finally{setBusy(false);}}}>
    {[['name','Name','text'],['email','Email','email'],['phone','Phone (optional)','tel']].map(([name,label,type])=><label key={name} className="block text-sm font-medium">{label}<input name={name} type={type} required={name!=='phone'} maxLength={name==='phone'?50:200} className="mt-1 block w-full rounded-lg border bg-transparent px-3 py-2"/></label>)}
    {link.terms&&<p className="whitespace-pre-wrap rounded-lg border p-4 text-sm">{link.terms}</p>}<label className="flex items-start gap-3 text-sm"><input name="consent" type="checkbox" required className="mt-1"/>I agree to share these details with this campaign’s business and be contacted about my enquiry. The referring participant will be recorded.</label><button type="submit" disabled={busy} className="rounded-lg bg-slate-900 px-5 py-3 text-white">{busy?'Submitting…':'Send enquiry'}</button>
  </form>}</main>;
}
