import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {trackerGet} from '../lib/tracker-client';
import {displayMinor} from '../lib/exact-commission';
import {Button} from '../components/ui';
export default function TrackerAgency(){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
  useEffect(()=>{const c=new AbortController();setError('');trackerGet('agency',{page:String(page)},c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[page,revision]);
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">Agency overview</h1><p className="mt-2 text-sm text-slate-500">Verified sub-accounts only. Exact financial totals stay separate by currency.</p></div><Button onClick={()=>setRevision(n=>n+1)}>Refresh</Button></div><Link to="/workspace-overview" className="inline-block text-brand-600 underline">Open current workspace overview</Link>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading verified workspaces…</p>}{data&&<><p className="text-sm text-slate-500">{data.scope==='agency'?'Agency access verified':'Showing only your current workspace; no wider agency authority is configured.'}</p><div className="grid gap-5 lg:grid-cols-2">{data.rows.map((t:any)=><section key={t.id} className="space-y-3 rounded-xl border p-6"><h2 className="text-lg font-semibold">{t.name}</h2><p className="text-sm text-slate-500">{t.locationId||'No GHL location mapped'} · Last sync {t.lastSync||'Not recorded'}</p><p>{t.cohort.leads} leads · {t.cohort.customers} customers</p>{t.receipts.map((r:any)=><p key={r.currency}>Net collected: {displayMinor(r.net_collected_minor,r.currency,t.minorDigits)}</p>)}{t.earnings.map((r:any)=><p key={r.currency}>Earned: {displayMinor(r.earned_minor,r.currency,t.minorDigits)} · Paid: {displayMinor(r.paid_minor,r.currency,t.minorDigits)}</p>)}{!t.receipts.length&&!t.earnings.length&&<p className="text-sm text-slate-500">No reviewed exact financial records yet.</p>}{t.locationId&&<a className="inline-block text-brand-600 underline" href={`https://app.gohighlevel.com/v2/location/${encodeURIComponent(t.locationId)}/dashboard`} target="_blank" rel="noreferrer">Open sub-account in GoHighLevel</a>}</section>)}</div><div className="flex gap-3"><Button disabled={page===1} onClick={()=>setPage(n=>n-1)}>Previous</Button><p>Page {page} · {data.total} workspaces</p><Button disabled={page*20>=data.total} onClick={()=>setPage(n=>n+1)}>Next</Button></div></>}</div>;
}
