import {useEffect,useState} from 'react';
import {trackerGet,trackerPost} from '../lib/tracker-client';
import {decimalToMinor,displayMinor,BENEFICIARIES,type ExactPlan,type ExactRule} from '../lib/exact-commission';
import {Button,Modal} from './ui';
export interface FormField {key:string;label:string;type?:string;options?:string[];resource?:string;optional?:boolean;help?:string}
export interface FormSpec {action:string;title:string;fields:FormField[];initial?:Record<string,any>;help?:string}
const control='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
export function Reference({field,value,onChange}:{field:FormField;value:any;onChange:(value:any)=>void}){
  const [q,setQ]=useState(''),[rows,setRows]=useState<any[]>([]),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController(),timer=setTimeout(()=>{trackerGet(field.resource!,{q,limit:'100'},c.signal).then(b=>{setRows(b.rows);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});},200);return()=>{clearTimeout(timer);c.abort();};},[q,field.resource]);
  if(field.type==='multi')return <div className="space-y-2"><input className={control} aria-label={`Search ${field.label}`} placeholder="Search participants" value={q} onChange={e=>setQ(e.target.value)}/><p className="text-xs">{(value||[]).length} selected. Search keeps previous selections.</p><div className="max-h-48 space-y-2 overflow-auto rounded-lg border p-3 dark:border-slate-700">{rows.map(r=><label key={r.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={(value||[]).includes(r.id)} onChange={e=>onChange(e.target.checked?[...(value||[]),r.id]:(value||[]).filter((i:string)=>i!==r.id))}/>{r.name||r.id} {r.email||''}</label>)}</div>{error&&<p role="alert">{error}</p>}</div>;
  return <div className="space-y-2"><input className={control} aria-label={`Search ${field.label}`} placeholder="Search by name or email" value={q} onChange={e=>setQ(e.target.value)}/><select className={control} multiple={field.type==='multi'} aria-label={field.label} required={!field.optional} value={value|| (field.type==='multi'?[]:'')} onChange={e=>onChange(field.type==='multi'?Array.from(e.target.selectedOptions).map(o=>o.value):e.target.value)}>
    {field.type!=='multi'&&<option value="">Select {field.label.toLowerCase()}</option>}{rows.map(r=><option key={r.id||r.external_id} value={r.id||r.external_id}>{r.name||r.contact_name||r.title||r.id} {r.version?`• v${r.version}`:''} {r.email?`• ${r.email}`:''}</option>)}</select>{value&&field.type!=='multi'&&<p className="text-xs text-slate-500">Selected: {rows.find(r=>(r.id||r.external_id)===value)?.name||'Saved selection'}</p>}{error&&<p role="alert">{error}</p>}</div>;
}
export function RuleEditor({value,onChange,currency,digits}:{value:ExactPlan|undefined;onChange:(p:ExactPlan)=>void;currency:string;digits:number}){
  const plan=value||{currency,minorDigits:digits,rules:[]};
  const change=(index:number,patch:Partial<ExactRule>)=>onChange({...plan,rules:plan.rules.map((r,i)=>i===index?{...r,...patch}:r)});
  const template=(kind:string)=>{const base:ExactRule={id:crypto.randomUUID(),name:'Collected revenue',event:'payment',kind:'percent',value:'1000',beneficiary:'referrer',base:'gross',chargeFrom:1,holdDays:30,group:'commission',stacking:'exclusive',priority:1};onChange({...plan,rules:kind==='lead'?[{...base,name:'Qualified lead award',event:'lead',kind:'fixed',value:'0'}]:kind==='setup'?[{...base,name:'Setup fee',productId:'setup',chargeTo:1},{...base,id:crypto.randomUUID(),name:'Recurring commission',productId:'subscription',priority:2,chargeTo:12}]:kind==='split'?[{...base,splits:[{beneficiary:'referrer',bps:5000},{beneficiary:'closer',bps:5000}]}]:[base]});};
  return <div className="space-y-4">{!plan.rules.length&&<div className="rounded-lg border p-4 dark:border-slate-700 dark:bg-slate-800/40"><p className="mb-2 text-sm">Start with a draft template and review every value before publishing.</p><div className="flex flex-wrap gap-2">{[['recurring','Recurring percentage'],['setup','Setup + 12 charges'],['lead','Qualified lead'],['split','Split commission pool']].map(([k,t])=><Button key={k} size="sm" variant="secondary" type="button" onClick={()=>template(k)}>{t}</Button>)}</div></div>}<p className="text-sm text-slate-500">Amounts use {currency}. Enter percentages as ordinary rates, such as 10 for 10%. Higher-priority rules have lower priority numbers. Net excludes tax and processing fees; collected gross already includes discounts.</p>{plan.rules.map((r,i)=><fieldset key={r.id} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><legend className="px-2 font-medium">Rule {i+1}</legend>
    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Name<input className={control} value={r.name} required onChange={e=>change(i,{name:e.target.value})}/></label>
    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Trigger<select className={control} value={r.event} onChange={e=>change(i,{event:e.target.value as ExactRule['event']})}>{Object.entries({payment:'Payment collected',sale:'First sale',lead:'Qualified lead',fixed_compensation:'Fixed compensation'}).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Calculation<select className={control} value={r.kind} onChange={e=>change(i,{kind:e.target.value as 'percent'|'fixed'})}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label>
    <label>{r.kind==='percent'?'Commission rate (%)':`Fixed amount (${currency})`}<DecimalInput key={r.kind} value={r.value} digits={r.kind==='percent'?2:digits} onChange={v=>change(i,{value:v})}/></label>
    <label>Beneficiary<select className={control} value={r.beneficiary} onChange={e=>change(i,{beneficiary:e.target.value as any})}>{BENEFICIARIES.map(v=><option key={v}>{v}</option>)}</select></label>
    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Calculation base<select className={control} value={r.base} onChange={e=>change(i,{base:e.target.value as any})}><option value="gross">Collected gross</option><option value="net">Net after tax and fees</option></select></label>
    <label className="block text-sm font-medium">Release timing<select className={control} value={r.releaseTiming||'days'} onChange={e=>change(i,{releaseTiming:e.target.value as ExactRule['releaseTiming']})}><option value="days">Hold days after earning</option><option value="month_end">Hold days after month end</option><option value="manual">Manual release with evidence</option></select></label>
    {[['chargeFrom','First qualifying charge'],['chargeTo','Last charge (blank = unlimited)'],['holdDays','Hold days']] .map(([k,label])=><label key={k} className="block text-sm font-medium text-slate-700 dark:text-slate-300">{label}<input type="number" min="0" className={control} value={(r as any)[k]??''} onChange={e=>change(i,{[k]:e.target.value===''?undefined:Number(e.target.value)})}/></label>)}
    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Product identifier (optional)<input className={control} value={r.productId||''} onChange={e=>change(i,{productId:e.target.value})}/></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Stacking group<input className={control} value={r.group} onChange={e=>change(i,{group:e.target.value})}/></label>
    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">Stacking policy<select className={control} value={r.stacking} onChange={e=>change(i,{stacking:e.target.value as any})}><option value="exclusive">First qualifying rule in group</option><option value="stack">Add every qualifying rule in group</option></select></label>
    <div className="sm:col-span-2"><p className="font-medium">Pool splits</p><p className="text-xs text-slate-500">Optional; shares must total 100%. No splits means the entire earning goes to the beneficiary above.</p>{(r.splits||[]).map((s,j)=><div key={j} className="my-2 flex gap-2"><select aria-label="Split beneficiary" className={control} value={s.beneficiary} onChange={e=>change(i,{splits:r.splits!.map((v,k)=>k===j?{...v,beneficiary:e.target.value as any}:v)})}>{BENEFICIARIES.map(v=><option key={v}>{v}</option>)}</select><DecimalInput label="Split percentage" digits={2} value={String(s.bps)} onChange={n=>change(i,{splits:r.splits!.map((v,k)=>k===j?{...v,bps:Number(n)}:v)})}/><Button type="button" onClick={()=>change(i,{splits:r.splits!.filter((_,k)=>k!==j)})}>Remove</Button></div>)}<Button size="sm" variant="secondary" type="button" onClick={()=>change(i,{splits:[...(r.splits||[]),{beneficiary:'referrer',bps:10000}]})}>Add split</Button></div>
    <div className="sm:col-span-2"><p className="text-sm font-medium">Receipt value tiers</p>{(r.tiers||[]).map((t,j)=><div key={j} className="my-2 flex gap-2"><DecimalInput label="Receipt threshold" digits={digits} value={t.thresholdMinor} onChange={n=>change(i,{tiers:r.tiers!.map((v,k)=>k===j?{...v,thresholdMinor:n}:v)})}/><DecimalInput label="Tier percentage" digits={2} value={String(t.bps)} onChange={n=>change(i,{tiers:r.tiers!.map((v,k)=>k===j?{...v,bps:Number(n)}:v)})}/><Button type="button" onClick={()=>change(i,{tiers:r.tiers!.filter((_,k)=>k!==j)})}>Remove</Button></div>)}<Button size="sm" variant="secondary" type="button" onClick={()=>change(i,{tiers:[...(r.tiers||[]),{thresholdMinor:'0',bps:1000}]})}>Add tier</Button></div>
    <Button size="sm" variant="secondary" type="button" onClick={()=>onChange({...plan,rules:plan.rules.filter((_,j)=>j!==i)})}>Remove rule</Button></fieldset>)}
    <Button size="sm" variant="secondary" type="button" onClick={()=>onChange({...plan,rules:[...plan.rules,{id:crypto.randomUUID(),name:'New commission rule',event:'payment',kind:'percent',value:'1000',beneficiary:'referrer',base:'gross',chargeFrom:1,holdDays:0,group:'commission',stacking:'exclusive',priority:plan.rules.length+1}]})}>Add commission rule</Button></div>;
}
export function TrackerForm({spec,onClose,onSave,currency,digits}:{spec:FormSpec;onClose:()=>void;onSave:(data:any)=>Promise<void>;currency:string;digits:number}){
  const [values,setValues]=useState<Record<string,any>>(spec.initial||{}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<any>(null);const set=(key:string,v:any)=>{setPreview(null);setValues(old=>({...old,[key]:v}));};
  return <Modal open title={spec.title} size="xl" onClose={()=>{if(!busy)onClose();}}><form className="space-y-5" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data={...values};for(const f of spec.fields){if(f.type==='money')data[f.key]=decimalToMinor(String(values[f.key]||'0'),digits);if(f.type==='number')data[f.key]=Number(values[f.key]);}if(['plan','payment','confirmReceipt','allocateReceipt'].includes(spec.action)&&!preview){setPreview(await trackerPost(spec.action,{...data,preview:true}));return;}await onSave(data);}catch(e){setError(e instanceof Error?e.message:'The change could not be saved.');}finally{setBusy(false);}}}>
    {spec.help&&<p className="text-sm text-slate-600 dark:text-slate-300">{spec.help}</p>}
    {spec.fields.map(f=><div key={f.key}><label className="mb-1 block text-sm font-medium" htmlFor={`tracker-${f.key}`}>{f.label}{f.optional?' (optional)':''}</label>{f.resource?<Reference field={f} value={values[f.key]} onChange={v=>set(f.key,v)}/>:f.type==='rules'?<RuleEditor value={values[f.key]} onChange={v=>set(f.key,v)} currency={currency} digits={digits}/>:f.type==='checkbox'?<input id={`tracker-${f.key}`} type="checkbox" checked={values[f.key]===true} onChange={e=>set(f.key,e.target.checked)}/>:f.options?<select id={`tracker-${f.key}`} className={control} required={!f.optional} value={values[f.key]||''} onChange={e=>set(f.key,e.target.value)}><option value="">Choose…</option>{f.options.map(v=><option key={v}>{v}</option>)}</select>:f.type==='textarea'?<textarea id={`tracker-${f.key}`} className={control} required={!f.optional} value={values[f.key]||''} onChange={e=>set(f.key,e.target.value)}/>:<input id={`tracker-${f.key}`} className={control} type={f.type==='money'?'text':f.type||'text'} inputMode={f.type==='money'?'decimal':undefined} required={!f.optional} value={values[f.key]??''} onChange={e=>set(f.key,e.target.value)}/>} {f.help&&<p className="mt-1 text-xs text-slate-500">{f.help}</p>}</div>)}
    {preview&&<section className="rounded-xl border border-brand-200 bg-brand-50 p-4 text-slate-900"><h3 className="font-med">Review before saving</h3>{spec.action==='plan'?<p className="mt-2 text-sm">{preview.historicalEarningsChanged} historical earnings will change. {preview.participants} participants have assignments on earlier versions; this new version needs a new dated assignment.</p>:<><p className="mt-2 text-sm">Collected amount: {displayMinor(preview.amountMinor,preview.currency,digits)}. Total commission: {displayMinor(preview.totalCommissionMinor,preview.currency,digits)}. Qualifying charge number: {preview.chargeNumber}.</p>{preview.earnings.map((e:any,i:number)=><p key={i} className="mt-2 text-xs">{e.explanation} Due {e.dueDate}.</p>)}</>}<p className="mt-2 text-xs">Nothing has been posted yet. Saving recalculates against current server data.</p></section>}
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}<div className="flex justify-end gap-3"><Button variant="secondary" type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Saving…':['plan','payment','confirmReceipt','allocateReceipt'].includes(spec.action)&&!preview?'Review changes':preview?'Confirm & Save':'Save'}</Button></div>
  </form></Modal>;
}

function DecimalInput({value,digits,onChange,label}:{value:string;digits:number;onChange:(v:string)=>void;label?:string}){
 const formatted=()=>{try{return displayMinor(value,'',digits).trim();}catch{return '';}};
 const [text,setText]=useState(formatted),[error,setError]=useState('');
 return <span><input aria-label={label} className={control} inputMode="decimal" required value={text} onChange={e=>{setText(e.target.value);try{const n=decimalToMinor(e.target.value,digits);onChange(n);setError('');e.target.setCustomValidity('');}catch(err){const message=(err as Error).message;setError(message);e.target.setCustomValidity(message);}}}/>{error&&<small role="alert">{error}</small>}</span>;
}
