import {GitBranch,RefreshCw,Plus,ArrowRight,FileText} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Button} from '../ui';
export function ProposalVersions({data,documentId,busy,money,onCreate,onClose}:{data:any;documentId:string;busy:boolean;money:(v:string)=>string;onCreate:(kind:string)=>void;onClose:()=>void}){
  const choices=[{kind:'revision',title:'Revise this offer',text:'Update products, pricing or terms in a separate draft.',icon:GitBranch,button:'Create revision'},{kind:'renewal',title:'Plan a renewal',text:'Prepare the next agreement for an approved client.',icon:RefreshCw,button:'Prepare renewal'},{kind:'expansion',title:'Grow the agreement',text:'Build a new offer for additional products or services.',icon:Plus,button:'Prepare expansion'}];
  return <div className="proposal-versions"><header><span className="notification-eyebrow">AGREEMENT HISTORY</span><h2>Versions & next steps</h2><p>Prepare your next offer while keeping every previous agreement intact.</p></header><div className="version-choices">{choices.map(c=><section key={c.kind}><c.icon size={22}/><h3>{c.title}</h3><p>{c.text}</p><Button variant={c.kind==='revision'?'primary':'secondary'} disabled={busy||(c.kind!=='revision'&&data.status!=='signed')} onClick={()=>onCreate(c.kind)}>{c.button}<ArrowRight size={14}/></Button>{c.kind!=='revision'&&data.status!=='signed'&&<small>Available after client approval</small>}</section>)}</div>
    {data.comparison&&<section className="version-comparison"><h3>What changed?</h3><p>Compared with {data.comparison.title}</p><div className="version-totals"><div><span>Previous first payment</span><strong>{money(data.comparison.beforeMinor)}</strong></div><ArrowRight size={20}/><div><span>Current first payment</span><strong>{money(data.comparison.afterMinor)}</strong></div></div><p className="notification-pill">{data.comparison.termsChanged?'Scope or terms updated':'Scope and terms unchanged'}</p><div className="st-table-wrap"><table className="st-table"><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th></tr></thead><tbody>{data.comparison.products.map((p:any,index:number)=><tr key={index}><td><strong>{p.name}</strong><small className="st-block">{!p.beforeQty?'Added':!p.afterQty?'Removed':p.beforeQty!==p.afterQty||p.beforePrice!==p.afterPrice?'Updated':'Unchanged'}</small></td><td>{p.beforeQty} → {p.afterQty}</td><td>{money(p.beforePrice)} → {money(p.afterPrice)}</td></tr>)}</tbody></table></div></section>}
    <section className="version-history"><h3>Version history</h3>{data.family.length?data.family.map((v:any,index:number)=><article key={v.id} className={v.id===documentId?'current':''}><span className="version-number"><FileText size={17}/></span><div><small>{v.revision_kind||'Original proposal'} · Version {index+1}</small><strong>{v.title}</strong></div><span className="notification-pill">{v.status==='signed'?'Approved':v.status}</span>{v.id===documentId?<span className="version-current">You are here</span>:<Link onClick={onClose} to={`/documents?proposal=${encodeURIComponent(v.id)}&workspace=versions`}>Open →</Link>}</article>):<p>This is the original proposal. New versions will appear here.</p>}</section><p className="proposal-caption">Creating a draft does not change a subscription, charge the client, or replace their existing approval.</p></div>;
}
