import {saveSalesman,importSalesmen,createStructure,preferences,mediaFolder,saveMediaFile,readFile,experienceRead} from './_lib/tracker-experience.js';
import type {VercelRequest,VercelResponse} from '@vercel/node';
import {getSessionUser} from './_lib/auth.js';
import {csrfOk} from './_lib/http.js';
import {hasDb} from './_lib/db.js';
import {ensureSchema} from './_lib/repository.js';
import {admin,audit,database,dateOnly,id,lock,participant,required,trackerInstalled,TrackerError,type SQL} from './_lib/tracker-common.js';
import {enroll,saveParticipant,saveTeam,publishPlan,assignPlan} from './_lib/tracker-people.js';
import {recordPayment,recordRefund,recordAward,recordAdjustment,allocateReceipt,closePartialPayout,createPayout,transitionPayout,settlePayout} from './_lib/tracker-finance.js';
import {createLead,editLead,attributeLead,attributionCandidate,saveOpportunity,saveCampaign,safeDestination} from './_lib/tracker-attribution.js';
import {listResource,report,exportResource} from './_lib/tracker-read.js';
import {simulateExact,minor} from '../src/lib/exact-commission.js';
import {previewSync,approveImport} from './_lib/tracker-sync.js';

export const config={maxDuration:60};
async function workspaceRead<T>(tenantId:string,fn:(db:SQL)=>Promise<T>){return database.transaction(async db=>{await db.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');const w=(await db.query('SELECT timezone FROM tracker_workspaces WHERE tenant_id=$1',[tenantId])).rows[0];if(w)await db.query("SELECT set_config('TimeZone',$1,true)",[w.timezone]);return fn(db);});}
export const mutations:Record<string,(db:SQL,u:any,b:any)=>Promise<any>>={
  salesman:saveSalesman,importSalesmen,structure:createStructure,preferences,mediaFolder,mediaFile:saveMediaFile,
  enroll,participant:saveParticipant,team:saveTeam,plan:publishPlan,assignment:assignPlan,
  lead:createLead,editLead,attribution:attributeLead,attributionCandidate,opportunity:saveOpportunity,campaign:saveCampaign,
  payment:recordPayment,refund:recordRefund,award:recordAward,adjustment:recordAdjustment,allocateReceipt,closePartialPayout,payout:createPayout,payoutAction:transitionPayout,settlement:settlePayout,approveImport,
  async confirmReceipt(db,u,b){admin(u);await lock(db,u.tenantId);const original=(await db.query('SELECT * FROM payments WHERE tenant_id=$1 AND id=$2 AND amount_minor IS NOT NULL',[u.tenantId,b.id])).rows[0];if(!original)throw new TrackerError('not_found','Receipt not found.');if(original.receipt_status==='confirmed')return{id:original.id,duplicate:true};if(original.receipt_status!=='pending')throw new TrackerError('invalid_status','Only pending receipts can be confirmed.');required(b.reason,'Confirmation evidence');const payload=JSON.parse(original.financial_inputs.requestFingerprint);const result=await recordPayment(db,u,{...payload,status:'confirmed',confirmExisting:true,...(b.preview?{preview:true}:{})});if(!b.preview)await audit(db,u,'payment',original.id,'confirmation_evidence',{reason:b.reason});return result;},
  async setup(db,u,b){admin(u);await lock(db,u.tenantId);if(!/^[A-Z]{3}$/.test(b.currency)||![0,2,3].includes(Number(b.minorDigits)))throw new TrackerError('invalid_currency','Select currency and decimal precision.');try{new Intl.DateTimeFormat('en',{timeZone:b.timezone}).format();}catch{throw new TrackerError('invalid_timezone','Select a valid IANA timezone.');}
    const current=(await db.query('SELECT * FROM tracker_workspaces WHERE tenant_id=$1',[u.tenantId])).rows[0];
    if(current&&(current.currency!==b.currency||Number(current.payout_terms?.minorDigits??2)!==Number(b.minorDigits))&&(await db.query('SELECT id FROM payments WHERE tenant_id=$1 AND amount_minor IS NOT NULL UNION ALL SELECT id FROM commission_ledger WHERE tenant_id=$1 AND amount_minor IS NOT NULL LIMIT 1',[u.tenantId])).rows.length)throw new TrackerError('currency_locked','Currency and decimal precision cannot change after exact financial records have been posted.');
    const terms={separateApprover:b.separateApprover!==false,method:'manual',minorDigits:Number(b.minorDigits),terms:String(b.terms||'')};
    if(b.separateApprover===false)required(b.reason,'Reason for changing approval policy');
    await db.query(`INSERT INTO tracker_workspaces(tenant_id,currency,timezone,payout_terms) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(tenant_id) DO UPDATE SET currency=EXCLUDED.currency,timezone=EXCLUDED.timezone,payout_terms=EXCLUDED.payout_terms`,[u.tenantId,b.currency,b.timezone,JSON.stringify(terms)]);await audit(db,u,'workspace',u.tenantId,'configured',{currency:b.currency,timezone:b.timezone,terms,reason:b.reason||null});return{ok:true};},
  async attributionPolicy(db,u,b){admin(u);await lock(db,u.tenantId);if(!['first','last'].includes(b.touch)||!Number.isInteger(Number(b.windowDays))||Number(b.windowDays)<1||Number(b.windowDays)>365)throw new TrackerError('invalid_policy','Choose first/last touch and a 1–365 day window.');const fields=String(b.fieldIds||'').split(',').map(s=>s.trim()).filter(Boolean);if(fields.length>50)throw new TrackerError('too_many_fields','Configure at most 50 fields.');required(b.reason,'Policy change reason');const current=(await db.query('SELECT attribution_policy FROM tracker_workspaces WHERE tenant_id=$1',[u.tenantId])).rows[0];if(!current)throw new TrackerError('setup_required','Configure the workspace first.');const policy={...current.attribution_policy,version:Number(current.attribution_policy.version||0)+1,touch:b.touch,windowDays:Number(b.windowDays),fieldIds:fields,evidencePriority:b.evidencePriority==='field_first'?'field_first':'code_first'};await db.query('UPDATE tracker_workspaces SET attribution_policy=$2::jsonb WHERE tenant_id=$1',[u.tenantId,JSON.stringify(policy)]);await audit(db,u,'attribution_policy',u.tenantId,'updated',{policy,reason:b.reason});return{ok:true};},
  async endAssignment(db,u,b){admin(u);await lock(db,u.tenantId);const end=dateOnly(b.effectiveTo);const r=await db.query('UPDATE plan_assignments SET effective_to=$3 WHERE tenant_id=$1 AND id=$2 AND effective_from<=$3::date AND (effective_to IS NULL OR effective_to>=$3::date) RETURNING id',[u.tenantId,b.id,end]);if(!r.rows.length)throw new TrackerError('invalid_assignment','Check assignment and end date.');await audit(db,u,'plan_assignment',b.id,'ended',{effectiveTo:end});return{ok:true};},
  async media(db,u,b){admin(u);if(b.campaignId&&!(await db.query('SELECT id FROM campaigns WHERE tenant_id=$1 AND id=$2',[u.tenantId,b.campaignId])).rows[0])throw new TrackerError('invalid_campaign','Campaign not found.');const resourceId=id('media');await db.query('INSERT INTO media_resources(id,tenant_id,campaign_id,title,url,description,audience,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[resourceId,u.tenantId,b.campaignId||null,required(b.title,'Title'),safeDestination(b.url),String(b.description||''),b.audience==='admin'?'admin':'participants',u.id]);await audit(db,u,'media',resourceId,'created',{});return{id:resourceId};},
  async goal(db,u,b){
    admin(u);const from=dateOnly(b.from),to=dateOnly(b.to);if(to<from||minor(b.targetMinor)<=0n||!['net_collected','commission_earned','attributed_leads','won_deals'].includes(b.metric))throw new TrackerError('invalid_goal','Choose a supported metric, positive target and date range.');
    if(b.salespersonId&&b.teamId)throw new TrackerError('invalid_scope','Choose either a participant or a team.');if(b.salespersonId)await participant(db,u,b.salespersonId);if(b.teamId&&!(await db.query('SELECT id FROM teams WHERE tenant_id=$1 AND id=$2',[u.tenantId,b.teamId])).rows.length)throw new TrackerError('invalid_team','Team not found.');
    const goalId=id('goal');await db.query(`INSERT INTO goals(id,tenant_id,scope_type,salesperson_id,team_id,metric,title,target_minor,currency,period,period_start,period_end,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'custom',$10,$11,$12)`,[goalId,u.tenantId,b.salespersonId?'salesperson':b.teamId?'team':'tenant',b.salespersonId||null,b.teamId||null,b.metric,required(b.title,'Goal title'),b.targetMinor,['attributed_leads','won_deals'].includes(b.metric)?null:required(b.currency,'Currency',3),from,to,u.id]);await audit(db,u,'goal',goalId,'created',{});return{id:goalId};
  },
  async archiveGoal(db,u,b){admin(u);const r=await db.query("UPDATE goals SET status='archived',updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id",[u.tenantId,b.id]);if(!r.rows.length)throw new TrackerError('not_found','Goal not found.',404);await audit(db,u,'goal',b.id,'archived',{});return{ok:true};},
  async milestone(db,u,b){admin(u);const g=(await db.query('SELECT target_minor FROM goals WHERE tenant_id=$1 AND id=$2',[u.tenantId,b.goalId])).rows[0];if(!g||g.target_minor===null||minor(b.thresholdMinor)<=0n||minor(b.thresholdMinor)>minor(String(g.target_minor)))throw new TrackerError('invalid_milestone','Choose a reviewed goal and a positive threshold up to its target.');const milestoneId=id('milestone');await db.query('INSERT INTO milestones(id,tenant_id,goal_id,title,threshold_minor,reward) VALUES($1,$2,$3,$4,$5,$6)',[milestoneId,u.tenantId,b.goalId,required(b.title,'Milestone title'),b.thresholdMinor,String(b.reward||'')]);await audit(db,u,'milestone',milestoneId,'created',{});return{id:milestoneId};},
  async release(db,u,b){
    admin(u);await lock(db,u.tenantId);const reason=required(b.reason,'Early release reason');
    const existing=(await db.query('SELECT released_override FROM commission_ledger WHERE tenant_id=$1 AND id=$2 AND amount_minor IS NOT NULL',[u.tenantId,b.id])).rows[0];if(existing?.released_override)return{ok:true,duplicate:true};
    const result=await db.query("UPDATE commission_ledger SET due_date=CURRENT_DATE::text,released_override=true WHERE tenant_id=$1 AND id=$2 AND status='pending' AND due_date>CURRENT_DATE::text AND amount_minor IS NOT NULL AND NOT EXISTS(SELECT 1 FROM payout_reservations p WHERE p.tenant_id=$1 AND p.entry_id=$2) RETURNING id",[u.tenantId,b.id]);if(!result.rows.length)throw new TrackerError('entry_unavailable','Only unreserved held exact earnings can be released.');await audit(db,u,'earning',b.id,'released_early',{reason});return{ok:true};
  },
};
export default async function handler(req:VercelRequest,res:VercelResponse){
  res.setHeader('Cache-Control','no-store');if(!['GET','POST'].includes(req.method||''))return res.status(405).json({error:'method_not_allowed'});
  if(!hasDb())return res.status(503).json({error:'database_not_configured'});
  try{await ensureSchema();const u=await getSessionUser(req);if(!u)return res.status(401).json({error:'unauthorized'});
    const installed=await trackerInstalled();const resource=String(req.query.resource||'status');
    if(req.method==='GET'&&resource==='status')return res.json({installed,workspace:installed?(await database.query('SELECT * FROM tracker_workspaces WHERE tenant_id=$1',[u.tenantId])).rows[0]||null:null});
    if(!installed)throw new TrackerError('migration_required','Sales Tracker requires the reviewed additive database migration. Existing live data remains available.',503);
    if(req.method==='GET'){
      if(resource==='agency'){
        admin(u);const own=(await database.query('SELECT agency_id FROM tenants WHERE id=$1',[u.tenantId])).rows[0];const agency=u.role==='owner'?own?.agency_id:null;
        const page=Math.max(1,Math.floor(Number(req.query.page)||1));const scope=agency?'agency_id=$1':'id=$1',param=agency||u.tenantId;
        const total=Number((await database.query(`SELECT count(*)::text AS n FROM tenants WHERE ${scope} AND status='active'`,[param])).rows[0].n);
        const tenants=(await database.query(`SELECT id,name,ghl_location_id,kleegr_last_sync_at FROM tenants WHERE ${scope} AND status='active' ORDER BY id LIMIT 20 OFFSET $2`,[param,(page-1)*20])).rows;
        const rows=[];for(const t of tenants){const summary=await workspaceRead(t.id,db=>report(db,{...u,tenantId:t.id},{})),w=(await database.query('SELECT payout_terms FROM tracker_workspaces WHERE tenant_id=$1',[t.id])).rows[0];rows.push({id:t.id,name:t.name,locationId:t.ghl_location_id,lastSync:t.kleegr_last_sync_at,minorDigits:w?.payout_terms?.minorDigits??2,receipts:summary.receipts,earnings:summary.earnings,cohort:summary.cohort});}
        return res.json({scope:agency?'agency':'tenant',rows,total,page});
      }
      if(resource==='file'){const file=await workspaceRead(u.tenantId,db=>readFile(db,u,String(req.query.id||'')));res.setHeader('Content-Type',file.mime);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`);return res.send(Buffer.from(file.content));}
      if(['preferences','folders','salesmen','overview'].includes(resource))return res.json(await workspaceRead(u.tenantId,db=>experienceRead(db,u,resource,req.query)));
      if(resource==='report')return res.json(await workspaceRead(u.tenantId,db=>report(db,u,req.query)));
      if(req.query.export==='csv'){res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${resource}.csv"`);return res.send(await workspaceRead(u.tenantId,db=>exportResource(db,u,resource,req.query)));}
      return res.json(await workspaceRead(u.tenantId,db=>listResource(db,u,resource,req.query)));
    }
    if(!csrfOk(req))return res.status(403).json({error:'csrf_check_failed'});
    const b=typeof req.body==='string'?JSON.parse(req.body):req.body||{};if(JSON.stringify(b).length>(b.action==='mediaFile'?2900000:b.action==='importSalesmen'?1000000:200000))throw new TrackerError('too_large','Request is too large.');
    if(b.action==='previewSync')return res.json(await previewSync(u,b.data||{}));
    if(b.action==='simulate'){admin(u);const s=b.data||b;const version=(await database.query('SELECT config FROM plan_versions WHERE tenant_id=$1 AND id=$2',[u.tenantId,s.versionId])).rows[0];if(!version)throw new TrackerError('not_found','Plan version not found.');return res.json({rows:simulateExact(version.config,{event:'payment',amountMinor:s.amountMinor,taxMinor:s.taxMinor||'0',feeMinor:s.feeMinor||'0',discountMinor:'0',currency:version.config.currency,productId:s.productId||'',chargeNumber:1,date:dateOnly(s.date),beneficiaries:{referrer:'estimated-referrer',owner:'estimated-owner',closer:'estimated-closer',parent:'estimated-parent',grandparent:'estimated-grandparent',...Object.fromEntries(Array.from({length:8},(_,i)=>[`tier_${i+3}`,`estimated-tier-${i+3}`]))}},s.months,s.newCustomers,s.churnBps),currency:version.config.currency,estimated:true,persisted:false});}
    const mutate=mutations[b.action];if(!mutate)throw new TrackerError('unknown_action','Action is not available.');
    return res.json(await database.transaction(async db=>{const w=(await db.query('SELECT timezone FROM tracker_workspaces WHERE tenant_id=$1',[u.tenantId])).rows[0];if(w)await db.query("SELECT set_config('TimeZone',$1,true)",[w.timezone]);return mutate(db,u,b.data||{});}));
  }catch(e){if(e instanceof TrackerError)return res.status(e.status).json({error:e.code,message:e.message});if(e instanceof SyntaxError)return res.status(400).json({error:'invalid_json',message:'Check the submitted fields.'});console.error('[tracker] Request failed');return res.status(400).json({error:'request_failed',message:e instanceof Error&& !('code' in e)?e.message:'The change could not be saved. Reload current data and retry.'});}
}
